---
permalink: upgrade/downloading-storagegrid-upgrade-files.html 
sidebar: sidebar 
keywords: download, upgrade files 
summary: StorageGRID 시스템을 업그레이드하기 전에 필요한 파일을 서비스 랩톱에 다운로드해야 합니다. 
---
= StorageGRID 업그레이드 파일을 다운로드하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템을 업그레이드하기 전에 필요한 파일을 서비스 랩톱에 다운로드해야 합니다.

.필요한 것
업그레이드하는 StorageGRID 소프트웨어 버전에 필요한 모든 핫픽스를 설치해야 합니다. 복구 및 유지 관리 지침의 핫픽스 절차를 참조하십시오.

.이 작업에 대해
를 다운로드해야 합니다 `.upgrade` 모든 플랫폼을 위한 아카이빙. Linux 호스트에 노드가 배포된 경우 업그레이드를 시작하기 전에 설치할 RPM 또는 DEB 아카이브도 다운로드해야 합니다.

.단계
. StorageGRID용 NetApp 다운로드 페이지로 이동합니다.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^]

. 최신 릴리스를 다운로드하려면 버튼을 선택하거나 드롭다운 메뉴에서 다른 버전을 선택하고 * GO * 를 선택합니다.
+
StorageGRID 소프트웨어 버전의 형식은 11._x. y _ 입니다. StorageGRID 핫픽스의 형식은 11._x.x.x.z _ 입니다.

. NetApp 계정의 사용자 이름과 암호를 사용하여 로그인합니다.
. Caution/MustRead 문이 나타나면 해당 문을 읽고 확인란을 선택합니다.
+
이 설명은 릴리스에 필요한 핫픽스가 있는 경우에 나타납니다.

. 최종 사용자 사용권 계약을 읽고 확인란을 선택한 다음 * 동의 및 계속 * 을 선택합니다.
+
선택한 버전의 다운로드 페이지가 나타납니다. 이 페이지에는 세 개의 열이 있습니다.

+
** StorageGRID를 설치합니다
** StorageGRID를 업그레이드합니다
** StorageGRID 어플라이언스에 대한 지원 파일


. Upgrade StorageGRID * 열에서 를 선택하여 다운로드합니다 `.upgrade` 아카이브:
+
모든 플랫폼에는 이 필요합니다 `.upgrade` 아카이브:

. Linux 호스트에 노드가 배포된 경우 RPM 또는 DEB 아카이브도 에서 다운로드합니다 `.tgz` 또는 `.zip` 형식.
+
업그레이드를 시작하기 전에 모든 Linux 노드에 RPM 또는 DEB 아카이브를 설치해야 합니다.

+

NOTE: SG100 또는 SG1000에는 추가 파일이 필요하지 않습니다.

+

NOTE: 를 선택합니다 `.zip` 파일 - 서비스 랩톱에서 Windows를 실행 중인 경우

+
** Red Hat Enterprise Linux 또는 CentOS+
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 를 누릅니다
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz`
** Ubuntu 또는 Debian+
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 를 누릅니다
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz`




.관련 정보
link:linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux: 모든 호스트에 RPM 또는 DEB 패키지 설치"]

link:../maintain/index.html["유지 및 복구"]
