---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: StorageGRID 11.5로의 업그레이드를 계획할 때는 업그레이드 기간을 기준으로 언제 업그레이드해야 할지 고려해야 합니다. 또한 업그레이드의 각 단계에서 수행할 수 있는 작업과 수행할 수 없는 작업을 알고 있어야 합니다. 
---
= 업그레이드를 완료하는 데 걸리는 시간 예상
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5로의 업그레이드를 계획할 때는 업그레이드 기간을 기준으로 언제 업그레이드해야 할지 고려해야 합니다. 또한 업그레이드의 각 단계에서 수행할 수 있는 작업과 수행할 수 없는 작업을 알고 있어야 합니다.

.이 작업에 대해
StorageGRID 업그레이드를 완료하는 데 필요한 시간은 클라이언트 로드 및 하드웨어 성능과 같은 다양한 요인에 따라 달라집니다.

이 표에는 주요 업그레이드 작업이 요약되어 있으며 각 작업에 필요한 대략적인 시간이 나와 있습니다. 표 다음에 나오는 단계에서는 시스템의 업그레이드 시간을 추정하는 데 사용할 수 있는 지침을 제공합니다.


IMPORTANT: StorageGRID 11.4에서 11.5로 업그레이드하는 동안 스토리지 노드의 Cassandra 데이터베이스 테이블이 업그레이드됩니다. 데이터베이스 업그레이드 * 작업은 백그라운드에서 수행되지만 완료하는 데 시간이 많이 필요할 수 있습니다. 데이터베이스를 업그레이드하는 동안 새 기능을 안전하게 사용하고 핫픽스를 적용하고 노드 복구 작업을 수행할 수 있습니다. 그러나 다른 유지보수 절차를 수행하지 못할 수 있습니다.


NOTE: 확장이 긴급하게 필요한 경우 11.5로 업그레이드하기 전에 확장을 수행하십시오.

[cols="1a,1a,1a,a"]
|===
| 업그레이드 작업 | 설명 | 필요한 대략적인 시간입니다 | 수행해야 합니다 


 a| 
업그레이드 서비스를 시작합니다
 a| 
업그레이드 사전 점검을 실행하고 소프트웨어 파일을 배포하며 업그레이드 서비스를 시작합니다.
 a| 
유효성 검사 오류가 보고되지 않은 경우 그리드 노드당 3분
 a| 
필요한 경우 예약된 업그레이드 유지 관리 기간 전에 수동으로 업그레이드 사전 점검을 실행할 수 있습니다.



 a| 
업그레이드 그리드 노드(기본 관리 노드)
 a| 
운영 관리자 노드가 중지, 업그레이드 및 재시작됩니다.
 a| 
최대 30분
 a| 
기본 관리자 노드에 액세스할 수 없습니다. 연결 오류가 보고되며 무시할 수 있습니다.



 a| 
업그레이드 그리드 노드(다른 모든 노드)
 a| 
다른 모든 그리드 노드의 소프트웨어는 노드를 승인하는 순서대로 업그레이드됩니다. 시스템의 모든 노드는 한 번에 하나씩 몇 분 동안 다운됩니다.
 a| 
노드당 15~45분, 어플라이언스 스토리지 노드를 가장 많이 사용해야 합니다

* 참고: * 어플라이언스 노드의 경우 StorageGRID 어플라이언스 설치 프로그램이 자동으로 최신 릴리즈로 업데이트됩니다.
 a| 
* 그리드 구성을 변경하지 마십시오.
* 감사 수준 구성을 변경하지 마십시오.
* ILM 구성을 업데이트하지 마십시오.
* 핫픽스, 서비스 해제 또는 확장과 같은 다른 유지보수 절차를 수행하지 마십시오.
+
* 참고: * 복구 절차를 수행해야 하는 경우 기술 지원 부서에 문의하십시오.





 a| 
기능 사용
 a| 
새 버전의 새 기능이 활성화됩니다.
 a| 
5분 미만
 a| 
* 그리드 구성을 변경하지 마십시오.
* 감사 수준 구성을 변경하지 마십시오.
* ILM 구성을 업데이트하지 마십시오.
* 다른 유지보수 절차를 수행하지 마십시오.




 a| 
데이터베이스 업그레이드
 a| 
모든 스토리지 노드에 있는 Cassandra 데이터베이스 테이블이 업그레이드됩니다.
 a| 
시스템에 있는 메타데이터의 양을 기준으로 한 시간 또는 일
 a| 
업그레이드 데이터베이스 * 작업 중에 업그레이드된 그리드는 정상적으로 작동하지만 업그레이드는 계속 진행 중입니다. 이 작업 중에 다음을 수행할 수 있습니다.

* 새 StorageGRID 버전의 새 기능을 사용합니다.
* 감사 수준 구성을 변경합니다.
* ILM 구성을 업데이트합니다.
* 핫픽스를 적용합니다.
* 노드 복구


* 참고: * 최종 업그레이드 단계 * 가 완료될 때까지 파기 또는 확장 절차를 수행할 수 없습니다.



 a| 
최종 업그레이드 단계
 a| 
임시 파일이 제거되고 새 릴리스로의 업그레이드가 완료됩니다.
 a| 
5분
 a| 
최종 업그레이드 단계 * 작업이 완료되면 모든 유지보수 절차를 수행할 수 있습니다.

|===
.단계
. 모든 그리드 노드를 업그레이드하는 데 필요한 시간을 예상합니다(* 데이터베이스 업그레이드 * 를 제외한 모든 업그레이드 작업을 고려합니다).
+
.. StorageGRID 시스템의 노드 수에 노드당 30분(평균)을 곱합니다.
.. 이 시간에 1시간을 추가하여 를 다운로드하는 데 필요한 시간을 고려하십시오 `.upgrade` 파일을 만들고, 사전 검사 검증을 실행하고, 최종 업그레이드 단계를 완료합니다.


. Linux 노드가 있는 경우 RPM 또는 DEB 패키지를 다운로드하고 설치하는 데 필요한 시간을 고려하여 각 노드에 대해 15분을 추가하십시오.
. 데이터베이스를 업그레이드하는 데 필요한 시간을 예상합니다.
+
.. 그리드 관리자에서 * 노드 * 를 선택합니다.
.. 트리에서 첫 번째 항목(전체 그리드)을 선택하고 * Storage * 탭을 선택합니다.
.. 커서를 * 스토리지 사용된 개체 메타데이터 * 차트 위에 놓고 * 사용된 * 값을 찾습니다. * 값은 개체 메타데이터의 바이트 수를 나타냅니다.
.. Used * 값을 1.5TB/일로 나누어 데이터베이스를 업그레이드하는 데 필요한 일수를 결정합니다.


. 1, 2, 3단계의 결과를 추가하여 총 업그레이드 예상 시간을 계산합니다.




== 예: StorageGRID 11.4에서 11.5로 업그레이드하는 데 걸리는 시간을 추정합니다

시스템에 14개의 그리드 노드가 있고 그 중 8개가 Linux 노드라고 가정합니다. 또한 객체 메타데이터에 * used * 값이 6TB라고 가정합니다.

. 14에 노드당 30분을 곱하고 1시간을 더합니다. 모든 노드의 업그레이드 예상 시간은 8시간입니다.
. Linux 노드에 RPM 또는 DEB 패키지를 설치하는 시간을 설명하기 위해 노드당 8 x 15분을 여러 번 수행합니다. 이 단계의 예상 시간은 2시간입니다.
. 6을 1.5TB/일로 나눕니다. 데이터베이스 업그레이드 * 작업의 예상 일 수는 4일입니다.
+

NOTE: 데이터베이스 업그레이드 * 작업을 실행하는 동안 새 기능을 안전하게 사용하고 핫픽스를 적용하고 노드 복구 작업을 수행할 수 있습니다.

. 값을 함께 추가합니다. 시스템 업그레이드를 StorageGRID 11.5.0으로 완료하는 데 5일이 소요됩니다.

