---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 업그레이드 중에 StorageGRID 시스템이 어떻게 영향을 받는지 알아야 합니다. 
---
= 업그레이드 중 시스템에 미치는 영향
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 중에 StorageGRID 시스템이 어떻게 영향을 받는지 알아야 합니다.



== StorageGRID 업그레이드는 무중단으로 수행할 수 있습니다

StorageGRID 시스템은 업그레이드 프로세스 전반에서 클라이언트 애플리케이션의 데이터를 수집하고 검색할 수 있습니다. 그리드 노드는 업그레이드 중에 한 번에 하나씩 다운되므로 모든 그리드 노드를 사용할 수 없는 시간은 없습니다.

지속적인 가용성을 보장하려면 적절한 ILM 정책을 사용하여 개체가 중복적으로 저장되도록 해야 합니다. 또한 모든 외부 S3 또는 Swift 클라이언트가 다음 중 하나로 요청을 보내도록 구성되어 있는지 확인해야 합니다.

* 고가용성(HA) 그룹으로 구성된 StorageGRID 끝점
* 고가용성 타사 로드 밸런서
* 각 클라이언트에 대해 여러 게이트웨이 노드가 있습니다
* 각 클라이언트에 대해 여러 스토리지 노드




== 어플라이언스 펌웨어가 업그레이드되었습니다

StorageGRID 11.5 업그레이드 중:

* 모든 StorageGRID 어플라이언스 노드는 StorageGRID 어플라이언스 설치 관리자 펌웨어 버전 3.5로 자동으로 업그레이드됩니다.
* SG6060 및 SGF6024 어플라이언스는 BIOS 펌웨어 버전 3B03.EX 및 BMC 펌웨어 버전 BMC 3.90.07로 자동 업그레이드됩니다.
* SG100 및 SG1000 어플라이언스는 BIOS 펌웨어 버전 3B08.EC 및 BMC 펌웨어 버전 4.64.07로 자동 업그레이드됩니다.




== 알림이 트리거될 수 있습니다

서비스가 시작 및 중지되거나 StorageGRID 시스템이 혼합 버전 환경으로 작동 중일 때(이전 버전을 실행하는 일부 그리드 노드와 이후 버전으로 업그레이드된 경우) 경고가 트리거될 수 있습니다. 예를 들어, 서비스 중지 시 * 노드 * 알림과 통신할 수 없음 * 알림이 표시되거나, 일부 노드가 StorageGRID 11.5로 업그레이드되었지만 다른 노드가 여전히 StorageGRID 11.4를 실행 중인 경우 * Cassandra 통신 오류 * 알림이 표시될 수 있습니다.

일반적으로 이러한 알림은 업그레이드가 완료되면 지워집니다.

업그레이드가 완료된 후 Grid Manager 대시보드에서 * Recently Resolved alerts * 를 선택하여 업그레이드 관련 경고를 검토할 수 있습니다.


NOTE: StorageGRID 11.5로 업그레이드하는 동안 스토리지 노드가 중지될 때 * ILM 배치를 달성 불가능한 * 경고가 트리거될 수 있습니다. 이 알림은 업그레이드가 성공적으로 완료된 후 1일 동안 지속될 수 있습니다.



== 많은 SNMP 알림이 생성됩니다

업그레이드 중에 그리드 노드를 중지하고 다시 시작할 때 많은 수의 SNMP 알림이 생성될 수 있습니다. 과도한 알림을 방지하려면 업그레이드를 시작하기 전에 SNMP 알림을 비활성화하려면 * SNMP 에이전트 알림 사용 * 확인란(* 구성 * > * 모니터링 * > * SNMP 에이전트 *)을 선택 취소합니다. 그런 다음 업그레이드가 완료된 후 알림을 다시 활성화합니다.



== 구성 변경이 제한됩니다

새 기능 사용 * 작업이 완료될 때까지 다음을 수행합니다.

* 그리드 구성을 변경하지 마십시오.
* 감사 수준 구성을 변경하지 마십시오.
* 새 기능을 사용하거나 사용하지 않도록 설정하지 마십시오.
* ILM 구성을 업데이트하지 마십시오. 그렇지 않으면 일관되지 않고 예기치 않은 ILM 동작이 발생할 수 있습니다.
* 핫픽스를 적용하거나 그리드 노드를 복구하지 마십시오.


최종 업그레이드 단계 * 작업이 완료될 때까지:

* 확장 절차를 수행하지 마십시오.
* 서비스 해제 절차를 수행하지 마십시오.

