---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, software upgrade 
summary: 소프트웨어 업그레이드 페이지에서는 필요한 파일을 업로드하고 StorageGRID 시스템의 모든 그리드 노드를 업그레이드하는 과정을 안내합니다. 
---
= 업그레이드를 수행하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
소프트웨어 업그레이드 페이지에서는 필요한 파일을 업로드하고 StorageGRID 시스템의 모든 그리드 노드를 업그레이드하는 과정을 안내합니다.

.필요한 것
다음 사항을 알고 있습니다.

* Grid Manager를 사용하여 기본 관리 노드에서 모든 데이터 센터 사이트의 모든 그리드 노드를 업그레이드해야 합니다.
* 문제를 감지하고 해결하려면 실제 업그레이드를 시작하기 전에 업그레이드 사전 점검을 수동으로 실행할 수 있습니다. 업그레이드를 시작할 때 동일한 사전 점검을 수행합니다. PreCheck 오류는 업그레이드 프로세스를 중지하며 문제를 해결하기 위해 기술 지원 부서의 개입이 필요할 수 있습니다.
* 업그레이드를 시작하면 기본 관리 노드가 자동으로 업그레이드됩니다.
* 운영 관리 노드를 업그레이드한 후 다음으로 업그레이드할 그리드 노드를 선택할 수 있습니다.
* 업그레이드를 완료하려면 StorageGRID 시스템의 모든 그리드 노드를 업그레이드해야 하지만, 개별 그리드 노드를 순서에 상관없이 업그레이드할 수 있습니다. 개별 그리드 노드, 그리드 노드 그룹 또는 모든 그리드 노드를 선택할 수 있습니다. 모든 사이트의 모든 그리드 노드가 업그레이드될 때까지 필요한 만큼 그리드 노드를 선택하는 프로세스를 반복할 수 있습니다.
* 그리드 노드에서 업그레이드가 시작되면 해당 노드의 서비스가 중지됩니다. 나중에 그리드 노드가 재부팅됩니다. 노드를 중지하고 재부팅할 준비가 되어 있는지 확실하지 않은 경우 그리드 노드의 업그레이드를 승인하지 마십시오.
* 모든 그리드 노드가 업그레이드되면 새 기능이 활성화되고 작업을 재개할 수 있습니다. 그러나 백그라운드 * 데이터베이스 업그레이드 * 작업 및 * 최종 업그레이드 단계 * 작업이 완료될 때까지 대기 상태로 또는 확장 절차를 수행해야 합니다.
* 처음에 사용한 동일한 하이퍼바이저 플랫폼에서 업그레이드를 완료해야 합니다.


.단계
. link:linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux: 모든 호스트에 RPM 또는 DEB 패키지 설치"]
. link:starting-upgrade.html["업그레이드를 시작하는 중입니다"]
. link:upgrading-grid-nodes-and-completing-upgrade.html["그리드 노드 업그레이드 및 업그레이드 완료"]
. link:increasing-metadata-reserved-space-setting.html["메타데이터 예약 공간 설정을 높입니다"]


.관련 정보
link:../admin/index.html["StorageGRID 관리"]

link:estimating-time-to-complete-upgrade.html["업그레이드를 완료하는 데 걸리는 시간 예상"]
