---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 업그레이드를 시작하기 전에 사용 가능한 최신 핫픽스가 적용된 이전 버전의 StorageGRID가 현재 설치되어 있는지 확인해야 합니다. 
---
= 설치된 StorageGRID 버전을 확인하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드를 시작하기 전에 사용 가능한 최신 핫픽스가 적용된 이전 버전의 StorageGRID가 현재 설치되어 있는지 확인해야 합니다.

.단계
. 지원되는 브라우저를 사용하여 Grid Manager에 로그인합니다.
. 도움말 * > * 정보 * 를 선택합니다.
. 버전*이 11.4._x.y_인지 확인합니다.
+
StorageGRID 11.4._x. y_version 번호:

+
** 주 릴리스는 0(11.4.0)의 _x_값을 가집니다.
** 사용 가능한 경우 부 릴리스에는 0 이외의 _x_값이 있습니다(예: 11.4.1).
** 핫픽스에 _y_값(예: 11.4.0.1)이 있습니다.


+

IMPORTANT: 이전 버전의 StorageGRID가 있는 경우 StorageGRID 11.5로 업그레이드하기 전에 11.4 버전으로 업그레이드해야 합니다. StorageGRID 11.5로 업그레이드하기 위해 가장 높은 11.4 부 버전 릴리즈일 필요는 없습니다.

. StorageGRID 11.4 버전이 아닌 경우 각 릴리스의 지침을 사용하여 한 번에 한 릴리스씩 버전 11.4로 업그레이드해야 합니다.
+
또한 다음 단계로 업그레이드하기 전에 각 StorageGRID 버전에 대한 최신 핫픽스를 적용해야 합니다.

+
이 예에는 가능한 업그레이드 경로가 하나 나와 있습니다.

. StorageGRID 11.4를 사용하는 경우 StorageGRID용 NetApp 다운로드 페이지로 이동하여 StorageGRID 11.4._x_버전에 사용 가능한 핫픽스가 있는지 확인합니다.
+
https://["NetApp 다운로드: StorageGRID"^]

. StorageGRID 11.4._x_version에 최신 핫픽스가 적용되어 있는지 확인합니다.
. 필요한 경우 StorageGRID 11.4._x_버전에 대한 최신 StorageGRID 11.4._x.y_HotFix를 다운로드하여 적용하십시오.
+
핫픽스 적용에 대한 자세한 내용은 복구 및 유지 관리 지침을 참조하십시오.





== 예: 버전 11.3.0.8에서 StorageGRID 11.5로의 업그레이드 준비

다음 예에서는 StorageGRID 버전 11.3.0.8에서 버전 11.5로의 업그레이드를 준비하는 업그레이드 단계를 보여 줍니다. StorageGRID 11.5로 업그레이드하기 전에 시스템에 최신 핫픽스가 설치된 StorageGRID 11.4 버전이 설치되어 있어야 합니다.

시스템을 업그레이드할 수 있도록 다음 순서로 소프트웨어를 다운로드하여 설치합니다.

. 최신 StorageGRID 11.3.0._y_HotFix를 적용합니다.
. StorageGRID 11.4.0 주요 릴리즈로 업그레이드하십시오. (11.4._x_minor 릴리스를 설치할 필요는 없습니다.)
. 최신 StorageGRID 11.4.0._y_HotFix를 적용합니다.


.관련 정보
link:../admin/index.html["StorageGRID 관리"]

link:../maintain/index.html["유지 및 복구"]
