---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: new features, 11.5, object lock, kmip, kms, ilm, decommission, node clone 
summary: StorageGRID 11.5에는 S3 오브젝트 잠금, KMIP 데이터 암호화 지원, ILM의 사용 편의성 향상, 재설계된 테넌트 관리자 사용자 인터페이스, StorageGRID 사이트 사용 중지 지원 및 어플라이언스 노드 클론 절차가 도입되었습니다. 
---
= StorageGRID 11.5의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5에는 S3 오브젝트 잠금, KMIP 데이터 암호화 지원, ILM의 사용 편의성 향상, 재설계된 테넌트 관리자 사용자 인터페이스, StorageGRID 사이트 사용 중지 지원 및 어플라이언스 노드 클론 절차가 도입되었습니다.



== 규정 준수 데이터를 위한 S3 오브젝트 잠금

StorageGRID 11.5의 S3 오브젝트 잠금 기능은 Amazon S3(Amazon Simple Storage Service)의 S3 오브젝트 잠금과 동등한 오브젝트 보호 솔루션입니다. StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정을 활성화하면 S3 테넌트 계정에서 S3 오브젝트 잠금이 설정된 버킷을 생성할 수 있습니다. 그런 다음 테넌트는 S3 클라이언트 애플리케이션을 사용하여 해당 버킷의 오브젝트에 대한 보존 및 법적 보류 설정을 선택적으로 지정할 수 있습니다.

S3 오브젝트 잠금을 사용하면 테넌트 사용자가 특정 오브젝트를 일정 시간 또는 무기한 보존해야 하는 규정을 준수할 수 있습니다.

.자세한 정보
* link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]
* link:../s3/index.html["S3을 사용합니다"]
* link:../tenant/index.html["테넌트 계정을 사용합니다"]




== KMS 암호화 키 관리

이제 그리드 관리자에서 하나 이상의 외부 키 관리 서버(KMS)를 구성하여 StorageGRID 서비스 및 스토리지 어플라이언스에 암호화 키를 제공할 수 있습니다. 각 KMS 또는 KMS 클러스터는 KMIP(Key Management Interoperability Protocol)를 사용하여 관련 StorageGRID 사이트의 어플라이언스 노드에 암호화 키를 제공합니다. 어플라이언스 볼륨이 암호화된 후에는 노드에서 KMS와 통신할 수 없는 한 어플라이언스의 데이터에 액세스할 수 없습니다.


NOTE: 암호화 키 관리를 사용하려면 어플라이언스를 그리드에 추가하기 전에 StorageGRID 어플라이언스 설치 프로그램을 사용하여 어플라이언스에 대한 * 노드 암호화 * 설정을 활성화해야 합니다.

.자세한 정보
* link:../admin/index.html["StorageGRID 관리"]




== ILM(정보 수명 주기 관리)을 위한 유용성 향상

* 이제 사용 중인 용량 및 사용 가능한 공간을 포함하여 스토리지 풀의 총 용량을 볼 수 있습니다. 스토리지 풀에 포함된 노드와 스토리지 풀을 사용하는 ILM 규칙 및 삭제 코딩 프로파일에서 확인할 수도 있습니다.
* 이제 둘 이상의 테넌트 계정에 적용되는 ILM 규칙을 설계할 수 있습니다.
* 삭제 코딩에 대한 ILM 규칙을 생성할 때 이제 매우 작은 오브젝트가 삭제 코딩되지 않도록 객체 크기(MB) 고급 필터를 0.2보다 크게 설정해야 합니다.
* 이제 ILM 정책 인터페이스를 통해 다른 규칙과 일치하지 않는 개체에 기본 ILM 규칙을 항상 사용할 수 있습니다. StorageGRID 11.5부터 기본 규칙은 기본 또는 고급 필터를 사용할 수 없으며 정책의 마지막 규칙으로 자동 설정됩니다.
+

NOTE: 현재 ILM 정책이 새로운 요구 사항을 준수하지 않는 경우 StorageGRID 11.5로 업그레이드한 후 계속 사용할 수 있습니다. 그러나 업그레이드 후 비준수 정책을 복제하려고 하면 필터를 포함하지 않는 기본 규칙을 선택하라는 메시지가 표시되고 정책의 끝에 기본 규칙을 배치해야 합니다.

* 새 ILM 규칙 또는 새 삭제 코딩 프로필을 생성할 때 기본적으로 모든 스토리지 노드 스탁 스토리지 풀이 더 이상 선택되지 않습니다. 또한 모든 스토리지 노드 스토리지 풀을 규칙에 사용되지 않는 한 제거할 수 있습니다.
+

NOTE: 이 스토리지 풀에는 모든 사이트가 포함되어 있으므로 모든 스토리지 노드 스토리지 풀을 사용하는 것은 권장되지 않습니다. 둘 이상의 사이트가 포함된 StorageGRID 시스템에서 이 스토리지 풀을 사용하는 경우 한 개체의 복사본을 여러 개 같은 사이트에 배치할 수 있습니다.

* 활성 또는 제안된 정책에서 사용되지 않는 한 재고 Make 2 Copies 규칙(모든 스토리지 노드 스토리지 풀을 사용)을 제거할 수 있습니다.
* 이제 Cloud Storage Pool에 저장된 객체를 즉시 삭제할 수 있습니다(동기식 삭제).


.자세한 정보
* link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]




== Grid Manager의 향상된 기능

* 재설계된 테넌트 계정 페이지를 사용하면 테넌트 계정 사용량을 보다 쉽게 확인할 수 있습니다. 이제 테넌트 요약 테이블에 사용된 공간, 할당량 사용률, 할당량 및 객체 수에 대한 열이 포함됩니다. 새로운 * 세부 정보 보기 * 버튼을 사용하면 각 테넌트의 개요와 계정의 S3 버킷 또는 Swift 컨테이너에 대한 세부 정보에 액세스할 수 있습니다. 또한 이제 두 개를 내보낼 수 있습니다 `.csv` 테넌트 사용을 위한 파일: 모든 테넌트의 사용 값이 포함된 파일 및 테넌트의 버킷 또는 컨테이너에 대한 세부 정보가 포함된 파일.
+
이 변경과 관련하여 테넌트 계정 사용을 추적하기 위해 다음과 같은 세 가지 새로운 Prometheus 메트릭이 추가되었습니다.

+
** `storagegrid_tenant_usage_data_bytes`
** `storagegrid_tenant_usage_object_count`
** `storagegrid_tenant_usage_quota_bytes`


* 관리 그룹 페이지(* 구성*>* 액세스 제어*)의 새* 액세스 모드* 필드를 사용하여 그룹에 대한 관리 권한이 읽기-쓰기(기본값) 또는 읽기 전용인지 여부를 지정할 수 있습니다. 읽기-쓰기 액세스 모드가 있는 그룹에 속한 사용자는 Grid Manager 및 Grid Management API에서 설정을 변경하고 작업을 수행할 수 있습니다. 읽기 전용 액세스 모드가 있는 그룹에 속한 사용자는 그룹에 대해 선택된 설정과 기능만 볼 수 있습니다.
+

NOTE: StorageGRID 11.5로 업그레이드하면 기존의 모든 관리 그룹에 대해 읽기-쓰기 액세스 모드 옵션이 선택됩니다.

* AutoSupport 사용자 인터페이스가 재설계되었습니다. 이제 그리드 관리자의 단일 페이지에서 이벤트 트리거, 사용자 트리거 및 주간 AutoSupport 메시지를 구성할 수 있습니다. AutoSupport 메시지의 추가 대상을 구성할 수도 있습니다.
+

NOTE: AutoSupport가 활성화되지 않은 경우 그리드 관리자 대시보드에 미리 알림 메시지가 나타납니다.

* 노드 페이지에서 * 스토리지 사용 - 오브젝트 데이터 * 차트를 보면 이제 복제된 오브젝트 데이터의 양과 그리드, 사이트 또는 스토리지 노드(* 노드 * > * _GRID/사이트/스토리지 노드 * > * 스토리지 *)에서 삭제 코딩 데이터의 양에 대한 추정치를 볼 수 있습니다.
* 옵션을 보다 쉽게 찾을 수 있도록 Grid Manager 메뉴 옵션이 재구성되었습니다. 예를 들어, 새 * 네트워크 설정 * 하위 메뉴가 * 구성 * 메뉴에 추가되었고 * 유지보수 * 및 * 지원 * 메뉴의 옵션이 이제 알파벳 순서로 나열됩니다.


.자세한 정보
* link:../admin/index.html["StorageGRID 관리"]




== 테넌트 관리자의 향상된 기능

* 테넌트 관리자 사용자 인터페이스의 모양과 구성이 사용자 환경을 개선하기 위해 완전히 재설계되었습니다.
* 새로운 테넌트 관리자 대시보드는 각 계정에 대한 상위 수준의 요약을 제공합니다. 버킷 세부 정보를 제공하고 버킷 또는 컨테이너, 그룹, 사용자 및 플랫폼 서비스 엔드포인트(구성된 경우)의 수를 표시합니다.


.자세한 정보
* link:../tenant/index.html["테넌트 계정을 사용합니다"]




== Prometheus 메트릭스 내보내기용 클라이언트 인증서

이제 클라이언트 인증서(* 구성 * > * 액세스 제어 * > * 클라이언트 인증서 *)를 업로드하거나 생성할 수 있습니다. 이 인증서는 StorageGRID Prometheus 데이터베이스에 대한 안전하고 인증된 액세스를 제공하는 데 사용할 수 있습니다. 예를 들어, Grafana를 사용하여 외부에서 StorageGRID를 모니터링해야 하는 경우 클라이언트 인증서를 사용할 수 있습니다.

.자세한 정보
* link:../admin/index.html["StorageGRID 관리"]




== 부하 분산 장치 개선 사항

* 사이트에서 라우팅 요청을 처리할 때 부하 분산 서비스는 이제 부하 인식 라우팅을 수행합니다. 즉, 동일한 사이트에 있는 스토리지 노드의 CPU 가용성을 고려합니다. 경우에 따라 CPU 가용성에 대한 정보는 로드 밸런서 서비스가 있는 사이트로 제한됩니다.
+

NOTE: 사이트에서 스토리지 노드의 최소 3분의 2가 StorageGRID 11.5로 업그레이드되고 CPU 통계를 보고할 때까지 CPU 인식이 활성화되지 않습니다.

* 보안을 강화하기 위해 이제 각 로드 밸런서 끝점에 대한 바인딩 모드를 지정할 수 있습니다. 끝점 고정 기능을 사용하면 각 끝점의 액세스 가능성을 특정 고가용성 그룹 또는 노드 인터페이스로 제한할 수 있습니다.


.자세한 정보
* link:../admin/index.html["StorageGRID 관리"]




== 개체 메타데이터가 변경됩니다

* * 새로운 실제 예약 공간 메트릭 *: 각 스토리지 노드에서 객체 메타데이터 공간 사용을 이해하고 모니터링할 수 있도록 스토리지 노드의 스토리지 사용된 객체 메타데이터 그래프(* 노드 * > * _스토리지 노드_ * > * 스토리지 *)에 새로운 Prometheus 메트릭이 표시됩니다.
+
[listing]
----
storagegrid_storage_utilization_metadata_reserved
----
+
실제 예약된 공간 * 메트릭은 StorageGRID가 특정 스토리지 노드의 개체 메타데이터에 예약된 공간을 나타냅니다.

* * 더 큰 스토리지 노드가 있는 설치의 경우 메타데이터 공간 증가 *: RAM이 128GB 이상인 스토리지 노드가 포함된 StorageGRID 시스템의 경우 시스템 전체 메타데이터 예약된 공간 설정이 다음과 같이 향상되었습니다.
+
** * 새 설치의 경우 8TB *: 새 StorageGRID 11.5 시스템을 설치하고 그리드의 각 스토리지 노드에 128MB 이상의 RAM이 있는 경우, 시스템 전체의 메타데이터 예약 공간 설정은 이제 3TB 대신 8TB로 설정됩니다.
** * 업그레이드용 4TB *: StorageGRID 11.5로 업그레이드하고 한 사이트의 각 스토리지 노드에 128MB 이상의 RAM이 있는 경우, 시스템 전체의 메타데이터 예약 공간 설정이 3TB 대신 4TB로 설정됩니다.
+
메타데이터 예약 공간 설정의 새 값은 이러한 대규모 스토리지 노드에 허용되는 메타데이터 공간을 최대 2.64TB까지 늘리고 적절한 메타데이터 공간을 향후 하드웨어 및 소프트웨어 버전에 예약하도록 합니다.

+
[NOTE]
====
스토리지 노드에 충분한 RAM이 있고 볼륨 0에 충분한 공간이 있는 경우 업그레이드 후 메타데이터 예약 공간 설정을 수동으로 최대 8TB까지 늘릴 수 있습니다. StorageGRID 11.5 업그레이드 후 추가 메타데이터 공간을 예약하면 향후 하드웨어 및 소프트웨어 업그레이드가 간소화됩니다.

link:increasing-metadata-reserved-space-setting.html["메타데이터 예약 공간 설정을 높입니다"]

====
+

NOTE: StorageGRID 시스템이 어떤 스토리지 노드에도 2.64TB 이상의 메타데이터를 저장(또는 저장할 것으로 예상되는 경우)하는 경우, 허용되는 메타데이터 공간을 늘릴 수 있습니다. 각 스토리지 노드에 스토리지 볼륨 0과 128GB 이상의 RAM에 사용 가능한 공간이 있는 경우 NetApp 어카운트 담당자에게 문의하십시오. NetApp에서 요구사항을 검토하고 가능한 경우 각 스토리지 노드에 대해 허용된 메타데이터 공간을 늘립니다.



* * 삭제된 메타데이터의 자동 정리 *: 스토리지 노드에 저장된 메타데이터 중 20% 이상이 제거될 준비가 되면(해당 객체가 삭제되었기 때문) StorageGRID는 이제 해당 스토리지 노드에 대해 자동 컴팩션을 수행할 수 있습니다. 이 백그라운드 프로세스는 사용 가능한 CPU, 디스크 공간 및 메모리가 있을 때 시스템의 로드가 적은 경우에만 실행됩니다. 새로운 컴팩션 프로세스는 삭제된 개체에 대한 메타데이터를 이전 릴리즈보다 빠르게 제거하고 새 오브젝트를 저장할 공간을 확보할 수 있도록 도와줍니다.


.자세한 정보
* link:../admin/index.html["StorageGRID 관리"]




== S3 REST API 지원으로 변경

* 이제 S3 REST API를 사용하여 지정할 수 있습니다 <<규정 준수 데이터를 위한 S3 오브젝트 잠금,S3 오브젝트 잠금>> 설정:
+
** S3 오브젝트 잠금이 활성화된 버킷을 생성하려면 와 함께 버킷 넣기 요청을 사용하십시오 `x-amz-bucket-object-lock-enabled` 머리글.
** 버킷에 대해 S3 오브젝트 잠금이 활성화되었는지 확인하려면 오브젝트 잠금 구성 가져오기 요청을 사용하십시오.
** S3 오브젝트 잠금이 설정된 버킷에 오브젝트 버전을 추가할 경우 다음 요청 헤더를 사용하여 보존 및 법적 보류 설정을 지정하십시오. `x-amz-object-lock-mode`, `x-amz-object-lock-retain-until-date`, 및 `x-amz-object-lock-legal-hold`.


* 이제 버전이 있는 버킷에서 여러 오브젝트 삭제를 사용할 수 있습니다.
* 이제 Put, Get 및 Delete Bucket 암호화 요청을 사용하여 기존 S3 버킷의 암호화를 관리할 수 있습니다.
* 의 필드 이름이 약간 변경되었습니다 `Expiration` 매개 변수. 수명 주기 구성의 만료 규칙이 특정 개체에 적용되는 경우 이 매개 변수는 Put Object, Head Object 또는 Get Object 요청에 대한 응답에 포함됩니다. 일치하는 만료 규칙을 나타내는 필드의 이름이 이전에 지정되었습니다 `rule_id`. 이 필드의 이름이 로 변경되었습니다 `rule-id` 구축하는 데 필요한 정보를 제공합니다.
* 기본적으로 S3 스토리지 사용 권한 가져오기 요청은 이제 강력한 글로벌 일관성을 사용하여 테넌트 계정 및 해당 버킷에서 사용되는 스토리지를 검색하려고 시도합니다. 강력한 글로벌 일관성을 달성할 수 없는 경우 StorageGRID는 강력한 사이트 일관성을 사용하여 사용 정보를 검색합니다.
* 를 클릭합니다 `Content-MD5` 이제 요청 헤더가 올바르게 지원됩니다.


.자세한 정보
* link:../s3/index.html["S3을 사용합니다"]




== CloudMirror 개체의 최대 크기는 5TB로 증가했습니다

CloudMirror 복제 서비스를 통해 대상 버킷에 복제할 수 있는 객체의 최대 크기는 5TB로 증가했으며, 이는 StorageGRID에서 지원하는 최대 객체 크기입니다.

.자세한 정보
* link:../s3/index.html["S3을 사용합니다"]
* link:../swift/index.html["Swift를 사용합니다"]




== 새 알림이 추가되었습니다

StorageGRID 11.5에 대해 다음과 같은 새 경고가 추가되었습니다.

* 어플라이언스 BMC 통신 오류입니다
* 어플라이언스 Fibre Channel 장애가 감지되었습니다
* 어플라이언스 Fibre Channel HBA 포트 오류입니다
* 어플라이언스 LACP 포트가 누락되었습니다
* Cassandra 자동 콤팩터 오류입니다
* Cassandra 자동 콤팩터 메트릭이 최신 상태가 아닙니다
* Cassandra 압축 과부하입니다
* 디스크 I/O가 매우 느립니다
* KMS CA 인증서 만료
* KMS 클라이언트 인증서 만료
* KMS 구성을 로드하지 못했습니다
* KMS 연결 오류입니다
* KMS 암호화 키 이름을 찾을 수 없습니다
* KMS 암호화 키 회전이 실패했습니다
* KMS가 구성되지 않았습니다
* 킬로미터 키가 어플라이언스 볼륨을 해독하지 못했습니다
* KMS 서버 인증서 만료
* 스토리지 풀의 사용 가능한 공간이 부족합니다
* 노드 네트워크 수신 프레임 오류입니다
* 서비스 어플라이언스의 스토리지 연결이 저하되었습니다
* 스토리지 어플라이언스 스토리지 접속 성능이 저하됨(이전에 어플라이언스 스토리지 접속 성능이 저하됨)
* 테넌트 할당량 사용량이 높습니다
* 예기치 않은 노드 재부팅


.자세한 정보
* link:../monitor/index.html["모니터링 및 문제 해결"]




== SNMP 트랩에 대한 TCP 지원

이제 SNMP 트랩 대상에 대한 프로토콜로 TCP(전송 제어 프로토콜)를 선택할 수 있습니다. 이전에는 UDP(User Datagram Protocol) 프로토콜만 지원되었습니다.

.자세한 정보
* link:../monitor/index.html["모니터링 및 문제 해결"]




== 설치 및 네트워킹 개선

* * MAC 주소 클로닝 *: 이제 MAC 주소 클로닝을 사용하여 특정 환경의 보안을 강화할 수 있습니다. MAC 주소 클로닝을 사용하면 그리드 네트워크, 관리 네트워크 및 클라이언트 네트워크에 전용 가상 NIC를 사용할 수 있습니다. Docker 컨테이너가 호스트의 전용 NIC의 MAC 주소를 사용하도록 하면 무차별 모드 네트워크 구성을 사용하지 않도록 할 수 있습니다. Linux 기반(베어 메탈) 노드의 노드 구성 파일에 3개의 새로운 MAC 주소 클로닝 키가 추가되었습니다.
* * DNS 및 NTP 호스트 경로의 자동 검색 *: 이전에는 클라이언트 네트워크에 모든 NTP 및 DNS 서버를 가질 수 없는 요구 사항과 같이 NTP 및 DNS 서버에 연결해야 하는 네트워크에 제한이 있었습니다. 이제 이러한 제한 사항이 제거되었습니다.


.자세한 정보
* link:../rhel/index.html["Red Hat Enterprise Linux 또는 CentOS를 설치합니다"]
* link:../ubuntu/index.html["Ubuntu 또는 Debian을 설치합니다"]




== 스토리지 노드 확장 후 EC(삭제 코딩) 데이터의 재조정 지원

EC 재조정 절차는 새 스토리지 노드를 추가한 후에 필요할 수 있는 새로운 명령줄 스크립트입니다. 이 절차를 수행할 때 StorageGRID는 삭제 코딩 조각을 사이트의 기존 스토리지 노드와 새로 확장된 스토리지 노드 간에 재배포합니다.


IMPORTANT: EC 재조정 절차는 제한된 경우에만 수행해야 합니다. 예를 들어, 확장 시 권장되는 스토리지 노드 수를 추가할 수 없는 경우 EC 재조정 절차를 사용하여 삭제 코딩 오브젝트를 추가로 저장할 수 있습니다.

.자세한 정보
* link:../expand/index.html["그리드를 확장합니다"]




== 새 유지보수 절차 및 수정된 유지보수 절차

* * 사이트 파기 *: 이제 StorageGRID 시스템에서 운영 사이트를 제거할 수 있습니다. 연결된 사이트의 서비스 해제 절차는 운영 사이트를 제거하고 데이터를 보존합니다. 새로운 서비스 해제 사이트 마법사는 프로세스를 안내합니다(* 유지 관리 * > * 서비스 해제 * > * 서비스 해제 사이트 *).
* * 어플라이언스 노드 클론 복제 *: 이제 기존 어플라이언스 노드를 복제하여 노드를 새 어플라이언스 모델로 업그레이드할 수 있습니다. 예를 들어, 용량이 작은 어플라이언스 노드를 용량이 큰 어플라이언스로 클론 복제할 수 있습니다. 또한 어플라이언스 노드를 복제하여 KMS 암호화에 필요한 새로운 * Node Encryption * 설정과 같은 새로운 기능을 구현할 수도 있습니다.
* * 프로비저닝 암호 변경 기능 *: 이제 프로비저닝 암호(* 구성 * > * 액세스 제어 * > * 그리드 암호 *)를 변경할 수 있습니다. 복구, 확장 및 유지 보수 절차에 필요한 암호 문구입니다.
* * 향상된 SSH 암호 동작 *: StorageGRID 어플라이언스의 보안을 강화하기 위해 어플라이언스를 유지보수 모드로 전환할 때 SSH 암호가 더 이상 변경되지 않습니다. 또한 노드를 StorageGRID 11.5로 업그레이드할 때 새로운 SSH 호스트 인증서와 호스트 키가 생성됩니다.
+

NOTE: StorageGRID 11.5로 업그레이드한 후 SSH를 사용하여 노드에 로그인하면 호스트 키가 변경되었다는 경고가 표시됩니다. 이 동작은 예상된 것으로, 새 키를 안전하게 승인할 수 있습니다.



.자세한 정보
* link:../maintain/index.html["유지 및 복구"]




== StorageGRID 어플라이언스 변경

* * 스토리지 어플라이언스용 SANtricity 시스템 관리자에 직접 액세스 *: 이제 StorageGRID 어플라이언스 설치 관리자 및 그리드 관리자에서 E-Series SANtricity 시스템 관리자 사용자 인터페이스에 액세스할 수 있습니다. 이러한 새로운 방법을 사용하면 어플라이언스의 관리 포트를 사용하지 않고 SANtricity System Manager에 액세스할 수 있습니다. 그리드 관리자에서 SANtricity 시스템 관리자에 액세스해야 하는 사용자는 새 스토리지 어플라이언스 관리자 권한이 있어야 합니다.
* * 노드 암호화 *: 새로운 KMS 암호화 기능의 일부로 StorageGRID 어플라이언스 설치 프로그램에 새로운 * 노드 암호화 * 설정이 추가되었습니다. 암호화 키 관리를 사용하여 어플라이언스 데이터를 보호하려면 어플라이언스 설치의 하드웨어 구성 단계에서 이 설정을 활성화해야 합니다.
* * UDP 포트 연결 *: 이제 외부 NFS 또는 DNS 서버에 사용되는 것과 같은 UDP 포트에 대한 StorageGRID 어플라이언스의 네트워크 연결을 테스트할 수 있습니다. StorageGRID 어플라이언스 설치 프로그램에서 * 네트워킹 구성 * > * 포트 연결 테스트(nmap) * 를 선택합니다.
* * 설치 및 구성 자동화 *: StorageGRID 어플라이언스 설치 프로그램에 새로운 JSON 구성 업로드 페이지가 추가되었습니다(* 고급 * > * 어플라이언스 구성 업데이트 *). 이 페이지에서는 하나의 파일을 사용하여 큰 그리드에 여러 어플라이언스를 구성할 수 있습니다. 또한 `configure-sga.py` StorageGRID 어플라이언스 설치 프로그램의 기능과 일치하도록 Python 스크립트가 업데이트되었습니다.


.자세한 정보
* link:../sg100-1000/index.html["SG100 및 AMP, SG1000 서비스 어플라이언스"]
* link:../sg6000/index.html["SG6000 스토리지 어플라이언스"]
* link:../sg5700/index.html["SG5700 스토리지 어플라이언스"]
* link:../sg5600/index.html["SG5600 스토리지 어플라이언스"]




== 감사 메시지의 변경

* * 덮어쓴 개체의 자동 정리 *: 이전에 덮어쓴 개체는 특정 경우에 디스크에서 제거되지 않았으며 이로 인해 공간이 추가로 소비되었습니다. 사용자가 액세스할 수 없는 덮어쓴 이러한 오브젝트는 이제 스토리지 공간을 절약하기 위해 자동으로 제거됩니다. 자세한 내용은 LKCU 감사 메시지를 참조하십시오.
* * S3 Object Lock * 에 대한 새로운 감사 코드: SPUT 감사 메시지에 포함할 네 개의 새로운 감사 코드가 추가되었습니다 <<규정 준수 데이터를 위한 S3 오브젝트 잠금,S3 오브젝트 잠금>> 요청 헤더:
+
** LKEN: 개체 잠금 활성화됨
** LKLH: 개체 잠금 법적 보류
** LKMD: 개체 잠금 보존 모드
** LKRU: Object Lock Retain until Date(객체 잠금 종료 날짜)


* * 마지막으로 수정한 시간 및 이전 개체 크기에 대한 새 필드 *: 이제 개체를 덮어쓴 시기와 원래 개체 크기를 추적할 수 있습니다.
+
** MTME(Last Modified Time) 필드가 다음 감사 메시지에 추가되었습니다.
+
*** SDEL(S3 삭제)
*** SPUT(S3 PUT)
*** WDEL(Swift 삭제)
*** WPUT(Swift PUT)


** CSIZ(Previous Object Size) 필드가 OVWR(Object Overwrite) 감사 메시지에 추가되었습니다.




.자세한 정보
* link:../audit/index.html["감사 로그를 검토합니다"]




== 새 NMS.requestlog 파일입니다

새 로그 파일, `/var/local/log/nms.requestlog`, 모든 관리 노드에서 유지 관리됩니다. 이 파일에는 관리 API에서 내부 StorageGRID 서비스로의 발신 연결에 대한 정보가 들어 있습니다.

.자세한 정보
* link:../monitor/index.html["모니터링 및 문제 해결"]




== StorageGRID 설명서 변경 사항

* 네트워킹 정보 및 요구 사항을 보다 쉽게 찾고 해당 정보가 StorageGRID 어플라이언스 노드에도 적용된다는 점을 명확히 하기 위해 네트워킹 문서는 소프트웨어 기반 설치 가이드(RedHat Enterprise Linux/CentOS, Ubuntu/Debian 및 VMware)에서 새로운 네트워킹 가이드로 옮겨졌습니다.
+
link:../network/index.html["네트워크 지침"]

* ILM 관련 지침 및 예제를 더 쉽게 찾을 수 있도록 정보 수명 주기 관리 개체를 관리하는 데 필요한 설명서가 _Administrator Guide_에서 새로운 ILM 가이드로 옮겨졌습니다.
+
link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

* 새로운 FabricPool 가이드에서는 StorageGRID를 NetApp FabricPool 클라우드 계층으로 구성하는 방법을 간략하게 설명하고, FabricPool 워크로드에 대한 ILM 및 기타 StorageGRID 옵션을 구성하는 모범 사례를 소개합니다.
+
link:../fabricpool/index.html["FabricPool용 StorageGRID를 구성합니다"]

* 이제 Grid Manager에서 여러 교육용 비디오에 액세스할 수 있습니다. 현재 동영상에서는 알림, 사용자 지정 알림, ILM 규칙 및 ILM 정책을 관리하는 지침을 제공합니다.

