---
permalink: sg100-1000/reviewing-appliance-network-connections-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, network connections, network connection, network, connection, grid, admin, client, bmc, management 
summary: StorageGRID 어플라이언스를 설치하기 전에 어플라이언스에 연결할 수 있는 네트워크를 이해해야 합니다. 
---
= 어플라이언스 네트워크 연결 검토
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 어플라이언스를 설치하기 전에 어플라이언스에 연결할 수 있는 네트워크를 이해해야 합니다.

StorageGRID 어플라이언스를 StorageGRID 시스템에 노드로 구축할 경우 다음 네트워크에 연결할 수 있습니다.

* * StorageGRID * 용 그리드 네트워크: 그리드 네트워크는 모든 내부 StorageGRID 트래픽에 사용됩니다. 그리드에서 모든 사이트 및 서브넷의 모든 노드 간에 연결을 제공합니다. 그리드 네트워크가 필요합니다.
* StorageGRID*용 관리자 네트워크: 관리자 네트워크는 시스템 관리 및 유지 보수에 사용되는 폐쇄된 네트워크입니다. 관리 네트워크는 일반적으로 사설 네트워크이며 사이트 간에 라우팅할 필요가 없습니다. 관리 네트워크는 선택 사항입니다.
* * StorageGRID용 클라이언트 네트워크: * 클라이언트 네트워크는 S3 및 Swift를 포함한 클라이언트 애플리케이션에 대한 액세스를 제공하는 데 사용되는 개방형 네트워크입니다. 클라이언트 네트워크는 그리드에 대한 클라이언트 프로토콜 액세스를 제공하므로 그리드 네트워크를 격리하고 보호할 수 있습니다. 이 네트워크를 통해 어플라이언스가 열려 있는 포트만 사용하여 액세스할 수 있도록 클라이언트 네트워크를 구성할 수 있습니다. 클라이언트 네트워크는 선택 사항입니다.
* 서비스 어플라이언스용 * BMC 관리 네트워크: * 이 네트워크는 SG100 및 SG1000의 베이스보드 관리 컨트롤러에 대한 액세스를 제공합니다. 이 네트워크를 사용하면 어플라이언스에서 하드웨어 구성요소를 모니터링하고 관리할 수 있습니다. 이 관리 네트워크는 StorageGRID용 관리 네트워크와 같을 수도 있고 독립 관리 네트워크일 수도 있습니다.


.관련 정보
link:gathering-installation-information-sg100-and-sg1000.html["설치 정보 수집(SG100 및 SG1000)"]

link:cabling-appliance-sg100-and-sg1000.html["어플라이언스 SG100 및 SG1000 케이블 연결)"]

link:../network/index.html["네트워크 지침"]

link:../primer/index.html["그리드 프라이머"]
