---
permalink: ubuntu/automating-installation-and-configuration-of-storagegrid-host-service.html 
sidebar: sidebar 
keywords:  
summary: Anabilities, Puppet, Chef, Fabric 또는 SaltStack과 같은 표준 오케스트레이션 프레임워크를 사용하여 StorageGRID 호스트 서비스의 설치를 자동화할 수 있습니다. 
---
= StorageGRID 호스트 서비스의 설치 및 구성 자동화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Anabilities, Puppet, Chef, Fabric 또는 SaltStack과 같은 표준 오케스트레이션 프레임워크를 사용하여 StorageGRID 호스트 서비스의 설치를 자동화할 수 있습니다.

StorageGRID 호스트 서비스는 DEB에 패키징되며 자동 설치를 활성화하기 위해 미리 준비하거나 프로그래밍 방식으로 준비할 수 있는 구성 파일에 의해 구동됩니다. 표준 오케스트레이션 프레임워크를 사용하여 Ubuntu 또는 Debian을 설치 및 구성하는 경우 플레이북이나 레시피에 StorageGRID를 추가하는 것이 간단해야 합니다.

다음과 같은 작업을 자동화할 수 있습니다.

. Linux를 설치하는 중입니다
. Linux 구성
. StorageGRID 요구 사항을 충족하도록 호스트 네트워크 인터페이스 구성
. StorageGRID 요구 사항을 충족하도록 호스트 스토리지 구성
. Docker 설치 중
. StorageGRID 호스트 서비스 설치
. 에서 StorageGRID 노드 구성 파일을 만드는 중입니다 `/etc/storagegrid/nodes`
. StorageGRID 노드 구성 파일의 유효성을 검사하는 중입니다
. StorageGRID 호스트 서비스를 시작합니다




== Ansible 역할 및 플레이북 예

예제 Ansible 역할 및 플레이북에는 /Extras 폴더에 설치 아카이브가 제공됩니다. Ansible 플레이북에서 방법을 확인할 수 있습니다 `storagegrid` 역할은 호스트를 준비하고 StorageGRID를 대상 서버에 설치합니다. 필요에 따라 역할 또는 플레이북을 사용자 지정할 수 있습니다.
