---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, ubuntu, debian, download installation files, downloading installation files 
summary: StorageGRID 설치 아카이브를 다운로드하고 필요한 파일을 추출해야 합니다. 
---
= StorageGRID 설치 파일 다운로드 및 추출
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 설치 아카이브를 다운로드하고 필요한 파일을 추출해야 합니다.

.단계
. StorageGRID용 NetApp 다운로드 페이지로 이동합니다.
+
https://["NetApp 다운로드: StorageGRID"^]

. 최신 릴리스를 다운로드하려면 버튼을 선택하거나 드롭다운 메뉴에서 다른 버전을 선택하고 * GO * 를 선택합니다.
. NetApp 계정의 사용자 이름과 암호를 사용하여 로그인합니다.
. Caution/MustRead 문이 나타나면 해당 문을 읽고 확인란을 선택합니다.
+
StorageGRID 릴리스를 설치한 후 필요한 핫픽스를 적용해야 합니다. 자세한 내용은 복구 및 유지 관리 지침의 핫픽스 절차를 참조하십시오.

. 최종 사용자 사용권 계약을 읽고 확인란을 선택한 다음 * 동의 및 계속 * 을 선택합니다.
+
선택한 버전의 다운로드 페이지가 나타납니다. 이 페이지에는 세 개의 열이 있습니다.

. StorageGRID* 설치 열에서 적절한 소프트웨어를 선택합니다.
+
를 선택합니다 `.tgz` 또는 `.zip` 플랫폼을 위한 아카이브 파일.

+
** `StorageGRID-Webscale-version-DEB-uniqueID.zip`
** `StorageGRID-Webscale-version-DEB-uniqueID.tgz`
+
압축된 파일에는 Ubuntu 또는 Debian용 DEB 파일 및 스크립트가 포함되어 있습니다.



+

NOTE: 를 사용합니다 `.zip` 파일 - 서비스 랩톱에서 Windows를 실행 중인 경우

. 아카이브 파일을 저장하고 압축을 풉니다.
. 다음 목록에서 필요한 파일을 선택합니다.
+
필요한 파일 세트는 계획된 그리드 토폴로지와 StorageGRID 그리드를 구축하는 방법에 따라 달라집니다.

+

NOTE: 표에 나열된 경로는 추출된 설치 아카이브에서 설치한 최상위 디렉토리에 상대적입니다.



[cols="1a,2a"]
|===
| 경로 및 파일 이름입니다 | 설명 


| ./debs/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| /debs/NLF000000.txt 를 참조하십시오  a| 
테스트 및 개념 증명 배포에 사용할 수 있는 비프로덕션 NetApp 라이센스 파일.



| /debs/storagegrid-webscale-images-version-SHA.deb 를 참조하십시오  a| 
StorageGRID 노드 이미지를 Ubuntu 또는 Debian 호스트에 설치하기 위한 DEB 패키지.



| /debs/storagegrid-webscale-images-version-SHA.deb.md5 를 참조하십시오  a| 
파일에 대한 MD5 체크섬입니다 `/debs/storagegrid-webscale-images-version-SHA.deb`.



| /debs/storagegrid-webscale-service-version-SHA.deb 를 참조하십시오  a| 
Ubuntu 또는 Debian 호스트에 StorageGRID 호스트 서비스를 설치하기 위한 DEB 패키지.



 a| 
* 배포 스크립팅 도구 *
 a| 
* 설명 *



| /debs/configure-storagegrid.py 를 참조하십시오  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| /debs/configure-sga.py 를 참조하십시오  a| 
StorageGRID 어플라이언스 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| /debs/storagegrid-ssoauth.py 를 참조하십시오  a| 
SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예제



| /debs/configure -StorageGrid.sample.json 을 참조하십시오  a| 
와 함께 사용할 샘플 구성 파일 `configure-storagegrid.py` 스크립트.



| /debs/configure -StorageGrid.blank.json 을 참조하십시오  a| 
와 함께 사용할 수 있는 빈 구성 파일입니다 `configure-storagegrid.py` 스크립트.



| ./debs/Extras/Ansible  a| 
StorageGRID 컨테이너 배포를 위한 Ubuntu 또는 Debian 호스트 구성을 위한 Ansible 역할 및 플레이북 예 필요에 따라 역할 또는 플레이북을 사용자 지정할 수 있습니다.

|===
.관련 정보
link:../maintain/index.html["유지 및 복구"]
