---
permalink: network/network-specific-requirements.html 
sidebar: sidebar 
keywords:  
summary: 각 StorageGRID 네트워크 유형에 대한 요구 사항을 따릅니다. 
---
= 네트워크 특정 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 StorageGRID 네트워크 유형에 대한 요구 사항을 따릅니다.



== 네트워크 게이트웨이 및 라우터

* 설정된 경우 해당 네트워크의 게이트웨이는 특정 네트워크의 서브넷 내에 있어야 합니다.
* 정적 주소 지정을 사용하여 인터페이스를 구성하는 경우 0.0.0.0이 아닌 게이트웨이 주소를 지정해야 합니다.
* 게이트웨이가 없는 경우 가장 좋은 방법은 게이트웨이 주소를 네트워크 인터페이스의 IP 주소로 설정하는 것입니다.




== 서브넷


IMPORTANT: 각 네트워크는 노드의 다른 네트워크와 겹치지 않는 자체 서브넷에 연결되어야 합니다.

배포 중에는 Grid Manager에서 다음과 같은 제한 사항이 적용됩니다. 사전 배포 네트워크 계획을 지원하기 위해 여기에 제공됩니다.

* 네트워크 IP 주소에 대한 서브넷 마스크는 255.255.255.254 또는 255.255.255.255(/31 또는 /32 CIDR 표기법)일 수 없습니다.
* 네트워크 인터페이스 IP 주소 및 서브넷 마스크(CIDR)에 의해 정의된 서브넷은 동일한 노드에 구성된 다른 인터페이스의 서브넷과 겹칠 수 없습니다.
* 각 노드의 그리드 네트워크 서브넷은 GNSL에 포함되어야 합니다.
* 관리 네트워크 서브넷은 그리드 네트워크 서브넷, 클라이언트 네트워크 서브넷 또는 GNSL의 모든 서브넷과 겹칠 수 없습니다.
* AESL에 있는 서브넷은 GNSL에 있는 서브넷과 겹칠 수 없습니다.
* 클라이언트 네트워크 서브넷은 그리드 네트워크 서브넷, 관리 네트워크 서브넷, GNSL의 모든 서브넷 또는 AESL의 모든 서브넷과 겹칠 수 없습니다.




== 그리드 네트워크

* 배포 시 각 그리드 노드는 그리드 네트워크에 연결되어 있어야 하며 노드를 배포할 때 지정한 네트워킹 구성을 사용하여 기본 관리 노드와 통신할 수 있어야 합니다.
* 정상적인 그리드 작업 중에 각 그리드 노드는 그리드 네트워크를 통해 다른 모든 그리드 노드와 통신할 수 있어야 합니다.
+

NOTE: 그리드 네트워크는 각 노드 간에 직접 라우팅할 수 있어야 합니다. 노드 간 NAT(Network Address Translation)는 지원되지 않습니다.

* 그리드 네트워크가 여러 개의 서브넷으로 구성된 경우 그리드 네트워크 서브넷 목록(GNSL)에 추가합니다. 정적 라우트는 GNSL의 각 서브넷에 대한 모든 노드에 생성됩니다.




== 관리자 네트워크

관리 네트워크는 선택 사항입니다. 관리 네트워크를 구성하려는 경우 다음 요구 사항 및 지침을 따르십시오.

관리 네트워크의 일반적인 사용에는 관리 연결, AutoSupport, KMS 및 NTP, DNS 및 LDAP와 같은 중요한 서버에 대한 연결(이러한 연결이 그리드 네트워크 또는 클라이언트 네트워크를 통해 제공되지 않는 경우)이 포함됩니다.


NOTE: 원하는 네트워크 서비스 및 클라이언트에 연결할 수 있는 경우 관리 네트워크 및 AESL은 각 노드에 고유할 수 있습니다.


NOTE: 외부 서브넷에서 인바운드 연결을 활성화하려면 관리자 네트워크에서 하나 이상의 서브넷을 정의해야 합니다. 정적 라우트는 AESL의 각 서브넷에 대해 자동으로 생성됩니다.



== 클라이언트 네트워크

클라이언트 네트워크는 선택 사항입니다. 클라이언트 네트워크를 구성하려는 경우 다음 고려 사항에 유의하십시오.

클라이언트 네트워크는 S3 및 Swift 클라이언트의 트래픽을 지원하도록 설계되었습니다. 구성된 경우 클라이언트 네트워크 게이트웨이는 노드의 기본 게이트웨이가 됩니다.

클라이언트 네트워크를 사용하는 경우 명시적으로 구성된 로드 밸런서 끝점에서만 인바운드 클라이언트 트래픽을 허용하여 악의적인 공격으로부터 StorageGRID를 보호할 수 있습니다. StorageGRID 관리 지침은 로드 밸런싱 관리 및 신뢰할 수 없는 클라이언트 네트워크 관리에 대한 정보를 참조하십시오.

.관련 정보
link:../admin/index.html["StorageGRID 관리"]
