---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: StorageGRID 플랫폼 서비스 또는 클라우드 스토리지 풀을 사용하려는 경우 대상 엔드포인트에 연결할 수 있도록 그리드 네트워킹 및 방화벽을 구성해야 합니다. 플랫폼 서비스에는 검색 통합, 이벤트 알림 및 CloudMirror 복제를 제공하는 외부 서비스가 포함됩니다. 
---
= 플랫폼 서비스 및 클라우드 스토리지 풀을 위한 네트워킹 및 포트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 플랫폼 서비스 또는 클라우드 스토리지 풀을 사용하려는 경우 대상 엔드포인트에 연결할 수 있도록 그리드 네트워킹 및 방화벽을 구성해야 합니다. 플랫폼 서비스에는 검색 통합, 이벤트 알림 및 CloudMirror 복제를 제공하는 외부 서비스가 포함됩니다.

플랫폼 서비스를 사용하려면 StorageGRID ADC 서비스를 외부 서비스 끝점에 호스팅하는 스토리지 노드로부터 액세스해야 합니다. 액세스 제공 예는 다음과 같습니다.

* ADC 서비스가 있는 스토리지 노드에서 대상 끝점으로 라우팅하는 AESL 항목을 사용하여 고유한 관리 네트워크를 구성합니다.
* 클라이언트 네트워크에서 제공하는 기본 경로를 사용합니다. 이 예제에서는 신뢰할 수 없는 클라이언트 네트워크 기능을 사용하여 인바운드 연결을 제한할 수 있습니다.


또한 클라우드 스토리지 풀에서는 Amazon S3 Glacier 또는 Microsoft Azure Blob 스토리지와 같이 사용되는 외부 서비스에서 제공하는 엔드포인트로 스토리지 노드에서 액세스할 수 있어야 합니다.

기본적으로 플랫폼 서비스 및 클라우드 스토리지 풀 통신에는 다음 포트가 사용됩니다.

* * 80 *: 로 시작하는 끝점 URI의 경우 `http`
* * 443 * : 로 시작하는 끝점 URI의 경우 `https`


끝점을 만들거나 편집할 때 다른 포트를 지정할 수 있습니다.

투명하지 않은 프록시 서버를 사용하는 경우에는 인터넷 끝점과 같은 외부 끝점으로 메시지를 보낼 수 있도록 프록시 설정도 구성해야 합니다. 프록시 설정을 구성하는 방법은 StorageGRID 관리 를 참조하십시오.

신뢰할 수 없는 클라이언트 네트워크에 대한 자세한 내용은 StorageGRID 관리 지침을 참조하십시오. 플랫폼 서비스에 대한 자세한 내용은 테넌트 계정 사용 지침을 참조하십시오. Cloud Storage Pool에 대한 자세한 내용은 정보 수명 주기 관리를 통해 개체 관리 지침을 참조하십시오.

.관련 정보
link:network-port-reference.html["네트워크 포트 참조"]

link:../primer/index.html["그리드 프라이머"]

link:../admin/index.html["StorageGRID 관리"]

link:../tenant/index.html["테넌트 계정을 사용합니다"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]
