---
permalink: tenant/duplicating-group.html 
sidebar: sidebar 
keywords: StorageGRID, tenant manager, tenant group, duplicating tenant group, duplicate tenant group 
summary: 기존 그룹을 복제하면 새 그룹을 더 빠르게 만들 수 있습니다. 
---
= 그룹 복제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 그룹을 복제하면 새 그룹을 더 빠르게 만들 수 있습니다.

.필요한 것
* 지원되는 브라우저를 사용하여 테넌트 관리자에 로그인해야 합니다.
* 루트 액세스 권한이 있는 사용자 그룹에 속해야 합니다.


.단계
. 액세스 관리 * > * 그룹 * 을 선택합니다.
. 복제할 그룹의 확인란을 선택합니다.
. Duplicate group * 을 선택합니다. 그룹을 생성하는 방법에 대한 자세한 내용은 S3 테넌트 또는 Swift 테넌트용 그룹을 생성하는 지침을 참조하십시오.
. 로컬 그룹을 생성하려면 * Local group * 탭을 선택하고, 이전에 구성된 ID 소스에서 그룹을 가져오려면 * Federated group * 탭을 선택합니다.
+
StorageGRID 시스템에서 SSO(Single Sign-On)를 사용하는 경우 로컬 그룹에 속한 사용자는 그룹 권한에 따라 클라이언트 애플리케이션을 사용하여 테넌트의 리소스를 관리할 수 있지만 테넌트 관리자에 로그인할 수 없습니다.

. 그룹의 이름을 입력합니다.
+
** * 로컬 그룹 *: 표시 이름과 고유 이름을 모두 입력합니다. 나중에 표시 이름을 편집할 수 있습니다.
** * 페더레이션 그룹 *: 고유한 이름을 입력합니다. Active Directory의 경우 고유한 이름은 에 연결된 이름입니다 `sAMAccountName` 속성. OpenLDAP의 경우 고유한 이름은 에 연결된 이름입니다 `uid` 속성.


. Continue * 를 선택합니다.
. 필요에 따라 이 그룹에 대한 권한을 수정합니다.
. Continue * 를 선택합니다.
. 필요에 따라 S3 테넌트에 대한 그룹을 복제할 경우 * S3 정책 추가 * 라디오 버튼에서 다른 정책을 선택할 수도 있습니다. 사용자 지정 정책을 선택한 경우 필요에 따라 JSON 문자열을 업데이트합니다.
. Create group * 을 선택합니다.


.관련 정보
link:creating-groups-for-s3-tenant.html["S3 테넌트에 대한 그룹 생성 중"]

link:creating-groups-for-swift-tenant.html["Swift 테넌트에 대한 그룹을 생성하는 중입니다"]

link:tenant-management-permissions.html["테넌트 관리 권한"]
