---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere에서 StorageGRID 그리드 노드 구축을 자동화할 수 있습니다. 
---
= VMware vSphere에서 그리드 노드 구축 자동화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere에서 StorageGRID 그리드 노드 구축을 자동화할 수 있습니다.

.필요한 것
* Bash 3.2 이상이 설치된 Linux/Unix 시스템에 액세스할 수 있습니다.
* VMware OVF Tool 4.1이 설치되고 올바르게 구성되었습니다.
* OVF 툴을 사용하여 VMware vSphere에 액세스하는 데 필요한 사용자 이름과 암호를 알고 있습니다.
* StorageGRID 가상 머신을 구축할 vSphere의 위치에 대한 VI(가상 인프라) URL을 알고 있습니다. 이 URL은 일반적으로 vApp 또는 리소스 풀이 됩니다. 예를 들면 다음과 같습니다. `vi://vcenter.example.com/vi/sgws`
+

NOTE: VMware를 사용할 수 있습니다 `ovftool` 유틸리티를 사용하여 이 값을 확인합니다( 참조) `ovftool` 문서 참조).

+

NOTE: vApp에 구축할 경우 가상 머신이 처음 시작될 때 자동으로 시작되지 않으며 수동으로 전원을 설정해야 합니다.

* 구성 파일에 필요한 모든 정보를 수집했습니다. 을 참조하십시오 link:collecting-information-about-your-deployment-environment.html["배포 환경에 대한 정보를 수집합니다"] 를 참조하십시오.
* StorageGRID용 VMware 설치 아카이브에서 다음 파일에 액세스할 수 있습니다.


[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| NetApp-SG-version-SHA.vmdk입니다  a| 
그리드 노드 가상 머신을 생성하기 위한 템플릿으로 사용되는 가상 머신 디스크 파일입니다.

* 참고: * 이 파일은 와 동일한 폴더에 있어야 합니다 `.ovf` 및 `.mf` 파일.



| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
Open Virtualization Format 템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| vsphere - non-primary-admin.ovf vsphere - non-primary-admin.mf  a| 
템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| vsphere-archive.ovf vsphere-archive.mf를 참조하십시오  a| 
템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| vsphere-storage.ovf vsphere-storage.mf  a| 
템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| deploy-vsphere-ovftool.sh  a| 
가상 그리드 노드의 배포를 자동화하는 데 사용되는 Bash 쉘 스크립트입니다.



| deploy-vsphere-ovftool-sample.ini  a| 
와 함께 사용할 샘플 구성 파일입니다 `deploy-vsphere-ovftool.sh` 스크립트.

|===