---
permalink: vmware/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords:  
summary: 그리드 노드를 구축하기 전에 네트워크 구성 및 VMware 환경에 대한 정보를 수집해야 합니다. 
---
= 배포 환경에 대한 정보를 수집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 노드를 구축하기 전에 네트워크 구성 및 VMware 환경에 대한 정보를 수집해야 합니다.



== VMware 정보입니다

배포 환경에 액세스하여 VMware 환경, 그리드, 관리자 및 클라이언트 네트워크용으로 생성된 네트워크, 스토리지 노드에 사용할 스토리지 볼륨 유형에 대한 정보를 수집해야 합니다.

다음을 포함하여 VMware 환경에 대한 정보를 수집해야 합니다.

* 구축을 완료할 수 있는 적절한 권한이 있는 VMware vSphere 계정의 사용자 이름 및 암호입니다.
* 각 StorageGRID 그리드 노드 가상 머신에 대한 호스트, 데이터 저장소 및 네트워크 구성 정보



IMPORTANT: VMware Live vMotion을 사용하면 가상 머신 클록 시간이 점프를 일으키며 모든 유형의 그리드 노드에서는 지원되지 않습니다. 드물지만 잘못된 클럭 시간으로 인해 데이터 또는 구성 업데이트가 손실될 수 있습니다.



== 그리드 네트워크 정보

StorageGRID 그리드 네트워크(필수)용으로 생성된 VMware 네트워크에 대한 정보를 수집해야 합니다. 여기에는 다음이 포함됩니다.

* 네트워크 이름입니다.
* DHCP를 사용하지 않는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이 및 네트워크 마스크)가 표시됩니다.
* DHCP를 사용하지 않는 경우 그리드 네트워크에 있는 기본 관리 노드의 IP 주소입니다. 자세한 내용은 ""그리드 노드가 기본 관리 노드를 검색하는 방법"을 참조하십시오.




== 관리자 네트워크 정보

선택적 StorageGRID 관리자 네트워크에 연결될 노드의 경우 이 네트워크에 대해 생성된 VMware 네트워크 관련 정보를 수집해야 합니다. 여기에는 다음이 포함됩니다.

* 네트워크 이름입니다.
* 고정 또는 DHCP 중 IP 주소를 할당하는 데 사용되는 방법입니다.
* 고정 IP 주소를 사용하는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이, 네트워크 마스크)가 표시됩니다.
* 관리 네트워크의 외부 서브넷 목록(ESL).




== 클라이언트 네트워크 정보

선택적 StorageGRID 클라이언트 네트워크에 연결될 노드의 경우 이 네트워크에 대해 생성된 VMware 네트워크 관련 정보를 수집해야 합니다. 여기에는 다음이 포함됩니다.

* 네트워크 이름입니다.
* 고정 또는 DHCP 중 IP 주소를 할당하는 데 사용되는 방법입니다.
* 고정 IP 주소를 사용하는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이, 네트워크 마스크)가 표시됩니다.




== 가상 스토리지 노드의 스토리지 볼륨

가상 머신 기반 스토리지 노드에 대한 다음 정보를 수집해야 합니다.

* 추가할 스토리지 볼륨(스토리지 LUN)의 수와 크기입니다. "스토리지 및 성능 요구 사항"을 참조하십시오.




== 그리드 구성 정보

그리드를 구성하려면 정보를 수집해야 합니다.

* 그리드 사용권
* NTP(Network Time Protocol) 서버 IP 주소입니다
* DNS(Domain Name System) 서버 IP 주소입니다


.관련 정보
link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리자 노드를 검색하는 방법"]

link:storage-and-performance-requirements.html["요구사항을 충족해야 합니다"]
