---
permalink: admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html 
sidebar: sidebar 
keywords:  
summary: 기본 StorageGRID 서버 인증서를 단일 사용자 지정 서버 인증서로 교체하여 보안 경고가 발생하지 않고 사용자가 그리드 관리자 및 테넌트 관리자에 액세스할 수 있도록 할 수 있습니다. 
---
= Grid Manager 및 테넌트 관리자에 대한 사용자 지정 서버 인증서 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 StorageGRID 서버 인증서를 단일 사용자 지정 서버 인증서로 교체하여 보안 경고가 발생하지 않고 사용자가 그리드 관리자 및 테넌트 관리자에 액세스할 수 있도록 할 수 있습니다.

.이 작업에 대해
기본적으로 모든 관리 노드에는 그리드 CA에서 서명한 인증서가 발급됩니다. 이러한 CA 서명 인증서는 하나의 공통 사용자 지정 서버 인증서 및 해당 개인 키로 대체할 수 있습니다.

단일 사용자 지정 서버 인증서가 모든 관리 노드에 사용되므로 클라이언트가 Grid Manager 및 Tenant Manager에 연결할 때 호스트 이름을 확인해야 하는 경우 인증서를 와일드카드 또는 다중 도메인 인증서로 지정해야 합니다. 사용자 지정 인증서를 정의하여 그리드의 모든 관리 노드와 일치시킵니다.

서버에서 구성을 완료해야 하며 사용 중인 루트 CA(인증 기관)에 따라 사용자가 그리드 관리자 및 테넌트 관리자에 액세스하는 데 사용할 웹 브라우저에 루트 CA 인증서를 설치해야 할 수도 있습니다.


NOTE: 실패한 서버 인증서로 인해 작업이 중단되지 않도록 하려면 이 서버 인증서가 만료될 때 * Management Interface * 용 서버 인증서 만료 알림과 레거시 관리 인터페이스 인증서 만료(MCEP) 경보가 모두 트리거됩니다. 필요에 따라 * 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택하여 현재 서비스 인증서가 만료될 때까지 일 수를 확인할 수 있습니다. 그런 다음 *_기본 관리 노드_ * > * CMN * > * 리소스 * 를 선택합니다.

[NOTE]
====
IP 주소 대신 도메인 이름을 사용하여 Grid Manager 또는 Tenant Manager에 액세스하는 경우, 다음 중 하나가 발생할 경우 브라우저에 인증서 오류가 표시되지 않고 무시하도록 옵션이 표시되지 않습니다.

* 사용자 지정 관리 인터페이스 서버 인증서가 만료됩니다.
* 사용자 지정 관리 인터페이스 서버 인증서를 기본 서버 인증서로 되돌립니다.


====
.단계
. 구성 * > * 네트워크 설정 * > * 서버 인증서 * 를 선택합니다.
. 관리 인터페이스 서버 인증서 섹션에서 * 사용자 정의 인증서 설치 * 를 클릭합니다.
. 필요한 서버 인증서 파일을 업로드합니다.
+
** * 서버 인증서 *: 사용자 정의 서버 인증서 파일 (`.crt`)를 클릭합니다.
** * 서버 인증서 개인 키 *: 사용자 지정 서버 인증서 개인 키 파일입니다 (`.key`)를 클릭합니다.
+

NOTE: EC 개인 키는 224비트 이상이어야 합니다. RSA 개인 키는 2048비트 이상이어야 합니다.

** * CA 번들 *: 각 중간 발급 CA(인증 기관)의 인증서를 포함하는 단일 파일입니다. 파일에는 인증서 체인 순서에 연결된 PEM 인코딩된 CA 인증서 파일이 각각 포함되어야 합니다.


. 저장 * 을 클릭합니다.
+
사용자 지정 서버 인증서는 이후의 모든 새 클라이언트 연결에 사용됩니다.

+
기본 StorageGRID 서버 인증서 또는 업로드된 CA 서명 인증서에 대한 자세한 정보를 표시하려면 탭을 선택합니다.

+

NOTE: 새 인증서를 업로드한 후 관련 인증서 만료 알림(또는 레거시 알람)이 지워지도록 최대 1일을 허용합니다.

. 페이지를 새로 고쳐 웹 브라우저가 업데이트되도록 합니다.

