---
permalink: admin/creating-tenant-account-if-sso-is-enabled.html 
sidebar: sidebar 
keywords:  
summary: '테넌트 계정을 생성할 때 이름, 클라이언트 프로토콜 및 선택적으로 스토리지 할당량을 지정합니다. StorageGRID에 대해 SSO(Single Sign-On)\ 를 사용하는 경우 테넌트 계정을 구성할 루트 액세스 권한이 있는 통합 그룹도 지정합니다.' 
---
= SSO가 활성화된 경우 테넌트 계정을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정을 생성할 때 이름, 클라이언트 프로토콜 및 선택적으로 스토리지 할당량을 지정합니다. StorageGRID에 대해 SSO(Single Sign-On)를 사용하도록 설정한 경우 테넌트 계정을 구성할 루트 액세스 권한이 있는 통합 그룹도 지정합니다.

.단계
. Display Name * (표시 이름 *) 텍스트 상자에 이 테넌트 계정의 표시 이름을 입력합니다.
+
표시 이름은 고유하지 않아도 됩니다. 테넌트 계정이 생성되면 고유한 숫자 계정 ID를 받습니다.

. 이 테넌트 계정에서 사용할 클라이언트 프로토콜을 * S3 * 또는 * Swift * 로 선택합니다.
. S3 테넌트 계정의 경우 이 테넌트에서 S3 버킷을 위한 플랫폼 서비스를 사용하지 않도록 하려면 * 플랫폼 서비스 허용 * 확인란을 선택한 상태로 유지합니다.
+
플랫폼 서비스가 설정된 경우 테넌트는 외부 서비스에 액세스하는 CloudMirror 복제와 같은 기능을 사용할 수 있습니다. 이러한 기능을 사용하지 않도록 설정하여 테넌트가 사용하는 네트워크 대역폭 또는 기타 리소스의 양을 제한할 수 있습니다. "플랫폼 서비스"를 참조하십시오.

. 스토리지 할당량 * 텍스트 상자에 원하는 경우 이 테넌트의 개체에 사용할 수 있도록 설정할 최대 기가바이트, 테라바이트 또는 페타 바이트 수를 입력합니다. 그런 다음 드롭다운 목록에서 단위를 선택합니다.
+
이 테넌트에 무제한 할당량을 사용하려면 이 필드를 비워 둡니다.

+

NOTE: 테넌트의 스토리지 할당량은 물리적 크기(디스크 크기)가 아닌 논리적 양(오브젝트 크기)을 나타냅니다. ILM 복사본 및 삭제 코딩은 사용된 할당량에 영향을 주지 않습니다. 할당량이 초과되면 테넌트 계정에서 새 객체를 생성할 수 없습니다.

+

NOTE: 각 테넌트 계정의 스토리지 사용량을 모니터링하려면 * Usage * 를 선택합니다. 또한 테넌트 계정은 테넌트 관리자의 대시보드 또는 테넌트 관리 API를 통해 자신의 스토리지 사용량을 모니터링할 수 있습니다. 노드가 그리드의 다른 노드로부터 격리되면 테넌트의 스토리지 사용량 값이 최신 상태가 아닐 수 있습니다. 네트워크 연결이 복원되면 합계가 업데이트됩니다.

. [고유 ID 소스 사용] 확인란이 선택 취소되어 비활성화되어 있습니다.
+
SSO가 활성화되어 있기 때문에 테넌트는 Grid Manager에 대해 구성된 ID 소스를 사용해야 합니다. 로컬 사용자는 로그인할 수 없습니다.

. [루트 액세스 그룹] * 필드의 그리드 관리자에서 기존 통합 그룹을 선택하여 테넌트에 대한 초기 루트 액세스 권한을 가집니다.
+

NOTE: 적절한 권한이 있는 경우 필드를 클릭하면 그리드 관리자의 기존 통합 그룹이 나열됩니다. 그렇지 않으면 그룹의 고유 이름을 입력합니다.

. 저장 * 을 클릭합니다.
+
테넌트 계정이 생성됩니다. 테넌트 계정 페이지가 나타나고 새 테넌트에 대한 행이 포함됩니다.

. 루트 액세스 그룹의 사용자인 경우 필요에 따라 새 테넌트에 대한 * 로그인 * 링크를 클릭하여 테넌트 관리자를 즉시 액세스하고 테넌트를 구성할 수 있습니다. 그렇지 않으면 * 로그인 * 링크의 URL을 테넌트 계정의 관리자에게 제공하십시오. (테넌트의 URL은 관리자 노드의 정규화된 도메인 이름 또는 IP 주소이며 그 뒤에 가 옵니다 `/?accountId=_20-digit-account-id_`참조)
+

NOTE: 로그인 * 을 클릭했지만 테넌트 계정의 루트 액세스 그룹에 속하지 않은 경우 액세스 거부 메시지가 표시됩니다.



.관련 정보
link:configuring-sso.html["Single Sign-On 구성"]

link:managing-platform-services-for-s3-tenant-accounts.html["S3 테넌트 계정에 대한 플랫폼 서비스 관리"]

link:../tenant/index.html["테넌트 계정을 사용합니다"]
