---
permalink: admin/generating-self-signed-certificate-for-management-interface.html 
sidebar: sidebar 
keywords:  
summary: 스크립트를 사용하여 엄격한 호스트 이름 확인이 필요한 관리 API 클라이언트용 자체 서명된 서버 인증서를 생성할 수 있습니다. 
---
= 관리 인터페이스에 대해 자체 서명된 서버 인증서를 생성하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스크립트를 사용하여 엄격한 호스트 이름 확인이 필요한 관리 API 클라이언트용 자체 서명된 서버 인증서를 생성할 수 있습니다.

.필요한 것
* 특정 액세스 권한이 있어야 합니다.
* 에 가 있어야 합니다 `Passwords.txt` 파일.


.이 작업에 대해
프로덕션 환경에서는 알려진 CA(인증 기관)에서 서명한 인증서를 사용해야 합니다. CA에서 서명한 인증서는 중단 없이 회전할 수 있습니다. 또한 중간자 공격에 대한 보호 기능이 강화되어 보안이 더욱 강화되고 있습니다.

.단계
. 각 관리 노드의 FQDN(정규화된 도메인 이름)을 얻습니다.
. 기본 관리자 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@primary_Admin_Node_IP`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
.. 루트로 전환하려면 다음 명령을 입력합니다. `su -`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 에서 변경됩니다 `$` 를 선택합니다 `#`.



. 자체 서명된 새 인증서를 사용하여 StorageGRID를 구성합니다.
+
`$ sudo make-certificate --domains _wildcard-admin-node-fqdn_ --type management`

+
** 용 `--domains`에서 와일드카드를 사용하여 모든 관리 노드의 정규화된 도메인 이름을 나타냅니다. 예를 들면, 다음과 같습니다. `*.ui.storagegrid.example.com` 와일드카드를 사용하여 나타냅니다 `admin1.ui.storagegrid.example.com` 및 `admin2.ui.storagegrid.example.com`.
** 설정 `--type` 를 선택합니다 `management` Grid Manager 및 Tenant Manager에서 사용하는 인증서를 구성합니다.
** 기본적으로 생성된 인증서는 1년(365일) 동안 유효하며 만료되기 전에 다시 만들어야 합니다. 를 사용할 수 있습니다 `--days` 기본 유효 기간을 재정의하는 인수입니다.
+

NOTE: 인증서의 유효 기간은 언제 시작됩니다 `make-certificate` 가 실행됩니다. 관리 API 클라이언트가 StorageGRID와 동일한 시간 소스와 동기화되어 있는지 확인해야 합니다. 그렇지 않으면 클라이언트가 인증서를 거부할 수 있습니다.

+
 $ sudo make-certificate --domains *.ui.storagegrid.example.com --type management --days 365
+
결과 출력에는 관리 API 클라이언트에 필요한 공용 인증서가 포함됩니다.



. 인증서를 선택하고 복사합니다.
+
선택 항목에 BEGIN 및 END 태그를 포함합니다.

. 명령 셸에서 로그아웃합니다. `$ exit`
. 인증서가 구성되었는지 확인합니다.
+
.. 그리드 관리자에 액세스합니다.
.. 구성 * * 서버 인증서 * 관리 인터페이스 서버 인증서 * 를 선택합니다.


. 복사한 공용 인증서를 사용하도록 관리 API 클라이언트를 구성합니다. BEGIN 및 END Tags를 포함합니다.

