---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords:  
summary: StorageGRID는 그리드 노드당 최대 3개의 네트워크 인터페이스를 지원하므로 각 개별 그리드 노드의 네트워킹을 보안 및 액세스 요구 사항에 맞게 구성할 수 있습니다. 
---
= StorageGRID 네트워크 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID는 그리드 노드당 최대 3개의 네트워크 인터페이스를 지원하므로 각 개별 그리드 노드의 네트워킹을 보안 및 액세스 요구 사항에 맞게 구성할 수 있습니다.


NOTE: 그리드 노드의 네트워크를 수정하거나 추가하려면 복구 및 유지 관리 지침을 참조하십시오. 네트워크 토폴로지에 대한 자세한 내용은 네트워킹 지침을 참조하십시오.



== 그리드 네트워크

필수 요소입니다. 그리드 네트워크는 모든 내부 StorageGRID 트래픽에 사용됩니다. 그리드에서 모든 사이트 및 서브넷의 모든 노드 간에 연결을 제공합니다.



== 관리자 네트워크

선택 사항. 관리 네트워크는 일반적으로 시스템 관리 및 유지 보수에 사용됩니다. 클라이언트 프로토콜 액세스에도 사용할 수 있습니다. 관리 네트워크는 일반적으로 사설 네트워크이며 사이트 간에 라우팅할 필요가 없습니다.



== 클라이언트 네트워크

선택 사항. 클라이언트 네트워크는 일반적으로 S3 및 Swift 클라이언트 애플리케이션에 대한 액세스를 제공하는 데 사용되는 개방형 네트워크이므로 그리드 네트워크를 격리하고 보호할 수 있습니다. 클라이언트 네트워크는 로컬 게이트웨이를 통해 연결할 수 있는 모든 서브넷과 통신할 수 있습니다.



== 지침

* 각 StorageGRID 그리드 노드에는 할당된 각 네트워크에 대한 전용 네트워크 인터페이스, IP 주소, 서브넷 마스크 및 게이트웨이가 필요합니다.
* 그리드 노드는 네트워크에 둘 이상의 인터페이스를 가질 수 없습니다.
* 네트워크 당, 그리드 노드별로 단일 게이트웨이가 지원되며 노드와 동일한 서브넷에 있어야 합니다. 필요한 경우 게이트웨이에서 보다 복잡한 라우팅을 구현할 수 있습니다.
* 각 노드에서 각 네트워크는 특정 네트워크 인터페이스에 매핑됩니다.
+
[cols="1a,1a"]
|===
| 네트워크 | 인터페이스 이름입니다 


 a| 
그리드
 a| 
eth0



 a| 
관리자(선택 사항)
 a| 
eth1



 a| 
클라이언트(선택 사항)
 a| 
eth2

|===
* 노드가 StorageGRID 어플라이언스에 연결된 경우 각 네트워크에 대해 특정 포트가 사용됩니다. 자세한 내용은 어플라이언스 설치 지침을 참조하십시오.
* 기본 라우트는 노드당 자동으로 생성됩니다. eth2가 활성화된 경우 0.0.0.0/0 은 eth2의 클라이언트 네트워크를 사용합니다. eth2가 활성화되지 않은 경우 0.0.0.0/0 은 eth0의 그리드 네트워크를 사용합니다.
* 그리드 노드가 그리드에 가입될 때까지 클라이언트 네트워크가 작동하지 않습니다
* 그리드 노드를 구축하는 동안 관리 네트워크를 구성하여 그리드를 완전히 설치하기 전에 설치 사용자 인터페이스에 액세스할 수 있습니다.


.관련 정보
link:../maintain/index.html["유지 및 복구"]

link:../network/index.html["네트워크 지침"]
