---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords:  
summary: '여러 가지 이유로 고가용성 \(HA\) 그룹을 사용할 수 있습니다.' 
---
= HA 그룹 사용 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여러 가지 이유로 고가용성(HA) 그룹을 사용할 수 있습니다.

* HA 그룹은 Grid Manager 또는 Tenant Manager에 대한 고가용성 관리 연결을 제공할 수 있습니다.
* HA 그룹은 S3 및 Swift 클라이언트에 고가용성 데이터 연결을 제공할 수 있습니다.
* 인터페이스가 하나만 포함된 HA 그룹을 사용하면 많은 VIP 주소를 제공하고 IPv6 주소를 명시적으로 설정할 수 있습니다.


그룹에 포함된 모든 노드가 동일한 서비스를 제공하는 경우에만 HA 그룹이 고가용성을 제공할 수 있습니다. HA 그룹을 생성할 때 필요한 서비스를 제공하는 노드 유형의 인터페이스를 추가합니다.

* * 관리 노드 *: 로드 밸런서 서비스를 포함하고 그리드 관리자 또는 테넌트 관리자에 대한 액세스를 활성화합니다.
* * 게이트웨이 노드 *: 로드 밸런서 서비스 및 CLB 서비스(더 이상 사용되지 않음)를 포함합니다.


[cols="1a,1a"]
|===
| HA 그룹의 용도 | 이 유형의 노드를 HA 그룹에 추가합니다 


 a| 
Grid Manager에 액세스합니다
 a| 
* 기본 관리자 노드(* 기본 마스터 *)
* 운영 관리자 노드가 아닌 노드


* 참고: * 기본 관리 노드는 기본 마스터여야 합니다. 일부 유지 보수 절차는 기본 관리 노드에서만 수행할 수 있습니다.



 a| 
테넌트 관리자에 대한 액세스만 가능합니다
 a| 
* 운영 또는 비운영 관리 노드




 a| 
S3 또는 Swift 클라이언트 액세스 -- 로드 밸런서 서비스
 a| 
* 관리자 노드
* 게이트웨이 노드




 a| 
S3 또는 Swift 클라이언트 액세스 -- CLB 서비스

* 참고: * CLB 서비스는 더 이상 사용되지 않습니다.
 a| 
* 게이트웨이 노드


|===


== Grid Manager 또는 Tenant Manager에 HA 그룹을 사용할 때의 제한 사항

Grid Manager 또는 테넌트 관리자에 대한 서비스 장애가 HA 그룹 내에서 페일오버를 트리거하지 않습니다.

페일오버가 발생했을 때 Grid Manager 또는 Tenant Manager에 로그인한 경우, 로그아웃되며 작업을 재개하려면 다시 로그인해야 합니다.

기본 관리 노드를 사용할 수 없는 경우 일부 유지 관리 절차를 수행할 수 없습니다. 장애 조치 중에 그리드 관리자를 사용하여 StorageGRID 시스템을 모니터링할 수 있습니다.



== CLB 서비스에 HA 그룹 사용 제한

CLB 서비스가 실패해도 HA 그룹 내에서 대체 작동이 트리거되지 않습니다.


NOTE: CLB 서비스는 더 이상 사용되지 않습니다.
