---
permalink: admin/managing-local-users.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 로컬 사용자 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로컬 사용자를 만들고 로컬 관리자 그룹에 할당하여 이러한 사용자가 액세스할 수 있는 그리드 관리자 기능을 결정할 수 있습니다.

Grid Manager에는 ""root""라는 이름의 미리 정의된 로컬 사용자가 하나 있습니다. 로컬 사용자를 추가 및 제거할 수는 있지만 루트 사용자는 제거할 수 없습니다.


NOTE: SSO(Single Sign-On)가 활성화된 경우 로컬 사용자는 StorageGRID에 로그인할 수 없습니다.

* 지원되는 브라우저를 사용하여 Grid Manager에 로그인해야 합니다.
* 특정 액세스 권한이 있어야 합니다.




== 로컬 사용자 생성

로컬 관리자 그룹을 생성한 경우 하나 이상의 로컬 사용자를 생성하고 각 사용자를 하나 이상의 그룹에 할당할 수 있습니다. 그룹의 권한은 사용자가 액세스할 수 있는 Grid Manager 기능을 제어합니다.

.이 작업에 대해
로컬 사용자만 생성할 수 있으며 이러한 사용자는 로컬 관리자 그룹에만 할당할 수 있습니다. 통합 사용자 및 통합 그룹은 외부 ID 소스를 사용하여 관리됩니다.

.단계
. Configuration * > * Access Control * > * Admin Users * 를 선택합니다.
. Create * 를 클릭합니다.
. 사용자의 표시 이름, 고유 이름 및 암호를 입력합니다.
. 액세스 권한을 제어하는 하나 이상의 그룹에 사용자를 할당합니다.
+
그룹 이름 목록은 그룹 테이블에서 생성됩니다.

. 저장 * 을 클릭합니다.


.관련 정보
link:managing-admin-groups.html["관리 그룹 관리"]



== 로컬 사용자 계정 수정

로컬 관리자 사용자 계정을 수정하여 사용자의 표시 이름 또는 그룹 구성원을 업데이트할 수 있습니다. 또한 사용자가 일시적으로 시스템에 액세스하지 못하도록 할 수도 있습니다.

.이 작업에 대해
로컬 사용자만 편집할 수 있습니다. 통합 사용자 세부 정보는 외부 ID 소스와 자동으로 동기화됩니다.

.단계
. Configuration * > * Access Control * > * Admin Users * 를 선택합니다.
. 편집할 사용자를 선택합니다.
+
시스템에 20개 이상의 항목이 포함된 경우 각 페이지에 한 번에 표시되는 행 수를 지정할 수 있습니다. 그런 다음 브라우저의 찾기 기능을 사용하여 현재 표시된 행에서 특정 항목을 검색할 수 있습니다.

. 편집 * 을 클릭합니다.
. 필요에 따라 이름 또는 그룹 구성원을 변경합니다.
. 선택적으로 사용자가 시스템에 일시적으로 액세스하지 못하게 하려면 * 액세스 거부 * 를 선택합니다.
. 저장 * 을 클릭합니다.
+
다음 번에 사용자가 로그아웃한 다음 그리드 관리자에 다시 로그인할 때 새 설정이 적용됩니다.





== 로컬 사용자 계정을 삭제하는 중입니다

더 이상 Grid Manager에 액세스할 필요가 없는 로컬 사용자의 계정을 삭제할 수 있습니다.

.단계
. Configuration * > * Access Control * > * Admin Users * 를 선택합니다.
. 삭제할 로컬 사용자를 선택합니다.
+

NOTE: 사전 정의된 루트 로컬 사용자는 삭제할 수 없습니다.

+
시스템에 20개 이상의 항목이 포함된 경우 각 페이지에 한 번에 표시되는 행 수를 지정할 수 있습니다. 그런 다음 브라우저의 찾기 기능을 사용하여 현재 표시된 행에서 특정 항목을 검색할 수 있습니다.

. 제거 * 를 클릭합니다.
. 확인 * 을 클릭합니다.




== 로컬 사용자 암호 변경

로컬 사용자는 Grid Manager 배너의 * Change Password * 옵션을 사용하여 자신의 암호를 변경할 수 있습니다. 또한 관리자 사용자 페이지에 액세스할 수 있는 사용자는 다른 로컬 사용자의 암호를 변경할 수 있습니다.

.이 작업에 대해
로컬 사용자의 암호만 변경할 수 있습니다. 통합 사용자는 외부 ID 원본에서 자신의 암호를 변경해야 합니다.

.단계
. Configuration * > * Access Control * > * Admin Users * 를 선택합니다.
. 사용자 페이지에서 사용자를 선택합니다.
+
시스템에 20개 이상의 항목이 포함된 경우 각 페이지에 한 번에 표시되는 행 수를 지정할 수 있습니다. 그런 다음 브라우저의 찾기 기능을 사용하여 현재 표시된 행에서 특정 항목을 검색할 수 있습니다.

. 암호 변경 * 을 클릭합니다.
. 암호를 입력 및 확인하고 * 저장 * 을 클릭합니다.

