---
permalink: admin/requirements-for-sso.html 
sidebar: sidebar 
keywords:  
summary: 'StorageGRID 시스템에 대해 SSO(Single Sign-On)\ 를 활성화하기 전에 이 섹션의 요구 사항을 검토하십시오.' 
---
= Single Sign-On 사용에 대한 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템에 대해 SSO(Single Sign-On)를 활성화하기 전에 이 섹션의 요구 사항을 검토하십시오.


IMPORTANT: 제한된 Grid Manager 또는 테넌트 관리자 포트에서는 SSO(Single Sign-On)를 사용할 수 없습니다. 사용자가 SSO(Single Sign-On)로 인증하도록 하려면 기본 HTTPS 포트(443)를 사용해야 합니다.



== ID 공급자 요구 사항

SSO의 ID 공급자(IDP)는 다음 요구 사항을 충족해야 합니다.

* 다음 AD FS(Active Directory Federation Service) 버전 중 하나:
+
** AD FS 4.0, Windows Server 2016에 포함되어 있습니다
+

NOTE: Windows Server 2016에서 을 사용해야 합니다 https://support.microsoft.com/en-us/help/3201845/cumulative-update-for-windows-10-version-1607-and-windows-server-2016["KB3201845 업데이트"^]또는 그 이상.

** AD FS 3.0, Windows Server 2012 R2 업데이트 이상에 포함되어 있습니다.


* TLS(전송 계층 보안) 1.2 또는 1.3
* Microsoft .NET Framework 버전 3.5.1 이상




== 서버 인증서 요구 사항

StorageGRID는 각 관리 노드의 관리 인터페이스 서버 인증서를 사용하여 그리드 관리자, 테넌트 관리자, 그리드 관리 API 및 테넌트 관리 API에 대한 액세스를 보호합니다. AD FS에서 StorageGRID에 대한 SSO 기반 당사자 트러스트를 구성하는 경우 서버 인증서를 AD FS에 대한 StorageGRID 요청에 대한 서명 인증서로 사용합니다.

관리 인터페이스에 대한 사용자 지정 서버 인증서를 아직 설치하지 않았다면 지금 설치해야 합니다. 사용자 지정 서버 인증서를 설치하면 모든 관리 노드에 사용되며 모든 StorageGRID 사용 상대 트러스트에 사용할 수 있습니다.


NOTE: AD FS 기반 당사자 신뢰에서 관리 노드의 기본 서버 인증서를 사용하는 것은 권장되지 않습니다. 노드가 실패하고 복구되면 새로운 기본 서버 인증서가 생성됩니다. 복구된 노드에 로그인하려면 먼저 AD FS의 기반 당사자 신뢰를 새 인증서로 업데이트해야 합니다.

노드의 명령 셸에 로그인하고 로 이동하여 관리 노드의 서버 인증서에 액세스할 수 있습니다 `/var/local/mgmt-api` 디렉토리. 사용자 지정 서버 인증서의 이름이 지정됩니다 `custom-server.crt`. 노드의 기본 서버 인증서 이름은 입니다 `server.crt`.

.관련 정보
link:controlling-access-through-firewalls.html["방화벽을 통한 액세스 제어"]

link:configuring-custom-server-certificate-for-grid-manager-tenant-manager.html["Grid Manager 및 테넌트 관리자에 대한 사용자 지정 서버 인증서 구성"]
