---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords:  
summary: S3 오브젝트 가져오기 요청을 사용하여 S3 버킷에서 오브젝트를 검색할 수 있습니다. 
---
= 객체 가져오기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 오브젝트 가져오기 요청을 사용하여 S3 버킷에서 오브젝트를 검색할 수 있습니다.



== PARTNUMBER 요청 매개 변수는 지원되지 않습니다

를 클릭합니다 `partNumber` 객체 가져오기 요청에 대해 요청 매개 변수가 지원되지 않습니다. 다중 파트 개체의 특정 부분을 검색하기 위한 가져오기 요청을 수행할 수 없습니다. 다음 메시지와 함께 501 미구현 오류가 반환됩니다.

[listing]
----
GET Object by partNumber is not implemented
----


== 고객이 제공한 암호화 키(SSE-C)를 사용하여 서버측 암호화를 위한 요청 헤더

사용자가 제공한 고유 키로 개체를 암호화한 경우 머리글 3개를 모두 사용합니다.

* `x-amz-server-side-encryption-customer-algorithm`을 지정합니다 `AES256`.
* `x-amz-server-side-encryption-customer-key`: 오브젝트의 암호화 키를 지정합니다.
* `x-amz-server-side-encryption-customer-key-MD5`: 오브젝트의 암호화 키에 대한 MD5 다이제스트를 지정합니다.



IMPORTANT: 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 오브젝트 데이터를 보호하기 전에 "'서버측 암호화 사용'의 고려 사항을 검토하십시오.



== 사용자 메타데이터의 UTF-8 문자

StorageGRID는 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자를 구문 분석하거나 해석하지 않습니다. 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자가 있는 개체에 대한 요청을 가져오면 가 반환되지 않습니다 `x-amz-missing-meta` 머리글 키 이름이나 값에 인쇄할 수 없는 문자가 포함된 경우.



== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않으며 반환됩니다 `XNotImplemented`:

* `x-amz-website-redirect-location`




== 버전 관리

가 있는 경우 `versionId` 하위 리소스가 지정되지 않았습니다. 작업이 버전 관리되는 버킷에서 개체의 최신 버전을 가져옵니다. 객체의 현재 버전이 삭제 마커인 경우 와 함께 ""찾을 수 없음" 상태가 반환됩니다 `x-amz-delete-marker` 응답 헤더가 로 설정되었습니다 `true`.



== Get Object for Cloud Storage Pool 개체의 동작

개체가 클라우드 스토리지 풀에 저장된 경우(정보 수명 주기 관리를 통해 개체 관리 지침 참조) 오브젝트 가져오기 요청의 동작은 개체의 상태에 따라 달라집니다. 자세한 내용은 " 헤드 개체 "를 참조하십시오.


NOTE: 객체가 클라우드 스토리지 풀에 저장되고 오브젝트 복사본이 하나 이상 그리드에 존재하는 경우, 객체 가져오기 요청은 클라우드 스토리지 풀에서 데이터를 검색하기 전에 그리드에서 데이터를 검색하려고 시도합니다.

|===
| 개체의 상태입니다 | Get Object의 동작입니다 


 a| 
StorageGRID로 수집되었지만 아직 ILM에 의해 평가되지 않은 오브젝트 또는 기존 스토리지 풀에 저장된 오브젝트 또는 삭제 코딩 사용
 a| 
`200 OK`

개체의 복사본이 검색됩니다.



 a| 
Cloud Storage Pool의 개체이지만 아직 검색할 수 없는 상태로 전환되지 않았습니다
 a| 
`200 OK`

개체의 복사본이 검색됩니다.



 a| 
개체가 검색할 수 없는 상태로 전환되었습니다
 a| 
`403 Forbidden`, `InvalidObjectState`

개체를 검색 가능한 상태로 복원하려면 POST 개체 복원 요청을 사용합니다.



 a| 
복구할 수 없는 상태에서 복원 중인 개체입니다
 a| 
`403 Forbidden`, `InvalidObjectState`

POST 개체 복원 요청이 완료될 때까지 기다립니다.



 a| 
객체가 클라우드 스토리지 풀에 완전히 복구되었습니다
 a| 
`200 OK`

개체의 복사본이 검색됩니다.

|===


== 클라우드 스토리지 풀에서 다중 또는 분할 오브젝트

여러 부분 개체를 업로드했거나 StorageGRID가 큰 개체를 세그먼트로 분할한 경우 StorageGRID는 개체의 부분 또는 세그먼트의 하위 집합을 샘플링하여 클라우드 저장소 풀에서 개체를 사용할 수 있는지 여부를 결정합니다. 경우에 따라 Get Object 요청이 잘못 반환될 수 있습니다 `200 OK` 개체의 일부 부분이 이미 복구할 수 없는 상태로 전환되었거나 개체의 일부 부분이 아직 복원되지 않은 경우

다음과 같은 경우:

* Get Object 요청이 일부 데이터를 반환하지만 전송 도중에 중지될 수 있습니다.
* 후속 Get Object 요청이 반환될 수 있습니다 `403 Forbidden`.


.관련 정보
link:using-server-side-encryption.html["서버 측 암호화 사용"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

link:post-object-restore.html["사후 개체 복원"]

link:s3-operations-tracked-in-audit-logs.html["감사 로그에서 S3 작업을 추적했습니다"]
