---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords:  
summary: S3 헤드 오브젝트 요청을 사용하여 오브젝트 자체를 반환하지 않고 오브젝트에서 메타데이터를 검색할 수 있습니다. 
---
= 헤드 개체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 헤드 오브젝트 요청을 사용하여 오브젝트 자체를 반환하지 않고 오브젝트에서 메타데이터를 검색할 수 있습니다. 객체가 클라우드 스토리지 풀에 저장된 경우 헤드 객체를 사용하여 객체의 전환 상태를 확인할 수 있습니다.



== 고객이 제공한 암호화 키(SSE-C)를 사용하여 서버측 암호화를 위한 요청 헤더

사용자가 제공한 고유 키로 개체를 암호화한 경우 이 헤더 3개를 모두 사용합니다.

* `x-amz-server-side-encryption-customer-algorithm`을 지정합니다 `AES256`.
* `x-amz-server-side-encryption-customer-key`: 오브젝트의 암호화 키를 지정합니다.
* `x-amz-server-side-encryption-customer-key-MD5`: 오브젝트의 암호화 키에 대한 MD5 다이제스트를 지정합니다.



IMPORTANT: 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 오브젝트 데이터를 보호하기 전에 "'서버측 암호화 사용'의 고려 사항을 검토하십시오.



== 사용자 메타데이터의 UTF-8 문자

StorageGRID는 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자를 구문 분석하거나 해석하지 않습니다. 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자가 있는 개체에 대한 head 요청은 을 반환하지 않습니다 `x-amz-missing-meta` 머리글 키 이름이나 값에 인쇄할 수 없는 문자가 포함된 경우.



== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않으며 반환됩니다 `XNotImplemented`:

* `x-amz-website-redirect-location`




== 클라우드 스토리지 풀 객체에 대한 응답 헤더입니다

객체가 클라우드 스토리지 풀에 저장된 경우(정보 수명 주기 관리를 통해 객체 관리 지침 참조) 다음 응답 헤더가 반환됩니다.

* `x-amz-storage-class: GLACIER`
* `x-amz-restore`


응답 헤더는 클라우드 스토리지 풀로 이동되는 오브젝트의 상태에 대한 정보를 제공하며, 선택적으로 검색할 수 없는 상태로 전환된 후 복구됩니다.

|===
| 개체의 상태입니다 | 헤드 객체에 대한 응답 


 a| 
StorageGRID로 수집되었지만 아직 ILM에 의해 평가되지 않은 오브젝트 또는 기존 스토리지 풀에 저장된 오브젝트 또는 삭제 코딩 사용
 a| 
`200 OK` (특별한 응답 헤더가 반환되지 않습니다.)



 a| 
Cloud Storage Pool의 개체이지만 아직 검색할 수 없는 상태로 전환되지 않았습니다
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2030 00:00:00 GMT"`

개체가 검색할 수 없는 상태로 전환될 때까지 의 값은 입니다 `expiry-date` 앞으로 어느 정도 먼 시간으로 설정됩니다. 정확한 전환 시간은 StorageGRID 시스템에 의해 제어되지 않습니다.



 a| 
개체가 검색할 수 없는 상태로 전환되었지만 하나 이상의 복사본이 그리드에 있습니다
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2030 00:00:00 GMT"`

의 값 `expiry-date` 앞으로 어느 정도 먼 시간으로 설정됩니다.

* 참고 *: 그리드의 복사본을 사용할 수 없는 경우(예: 스토리지 노드가 다운된 경우), 객체를 성공적으로 검색하기 전에 POST 객체 복원 요청을 발행하여 클라우드 스토리지 풀에서 복제본을 복원해야 합니다.



 a| 
개체가 검색할 수 없는 상태로 전환되었으며 그리드에 복사본이 없습니다
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`



 a| 
복구할 수 없는 상태에서 복원 중인 개체입니다
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="true"`



 a| 
객체가 클라우드 스토리지 풀에 완전히 복구되었습니다
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2018 00:00:00 GMT"`

를 클릭합니다 `expiry-date` 클라우드 스토리지 풀의 객체가 검색 불가능한 상태로 반환되는 시점을 나타냅니다.

|===


== 클라우드 스토리지 풀에서 다중 또는 분할 오브젝트

여러 부분 개체를 업로드했거나 StorageGRID가 큰 개체를 세그먼트로 분할한 경우 StorageGRID는 개체의 부분 또는 세그먼트의 하위 집합을 샘플링하여 클라우드 저장소 풀에서 개체를 사용할 수 있는지 여부를 결정합니다. 경우에 따라 헤드 객체 요청이 잘못 반환될 수 있습니다 `x-amz-restore: ongoing-request="false"` 개체의 일부 부분이 이미 복구할 수 없는 상태로 전환되었거나 개체의 일부 부분이 아직 복원되지 않은 경우



== 버전 관리

가 있는 경우 `versionId` 하위 리소스가 지정되지 않았습니다. 작업이 버전 관리되는 버킷에서 개체의 최신 버전을 가져옵니다. 객체의 현재 버전이 삭제 마커인 경우 와 함께 ""찾을 수 없음" 상태가 반환됩니다 `x-amz-delete-marker` 응답 헤더가 로 설정되었습니다 `true`.

.관련 정보
link:s3-rest-api-supported-operations-and-limitations.html["서버 측 암호화 사용"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

link:post-object-restore.html["사후 개체 복원"]

link:s3-operations-tracked-in-audit-logs.html["감사 로그에서 S3 작업을 추적했습니다"]
