---
permalink: s3/storagegrid-s3-rest-api-operations.html 
sidebar: sidebar 
keywords:  
summary:  
---
= StorageGRID S3 REST API 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템별 S3 REST API에 작업이 추가됩니다.



== 버킷 정합성 보장 요청 가져오기

Get Bucket 정합성 보장 요청을 사용하면 특정 버킷에 적용되는 정합성 보장 수준을 확인할 수 있습니다.

기본 정합성 보장 컨트롤은 새로 생성된 객체에 대해 읽기/쓰기 작업을 보장하도록 설정됩니다.

이 작업을 완료하려면 S3:GetBucketConsistency 권한이 있거나 계정 루트여야 합니다.



=== 요청 예

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== 응답

응답 XML에서 `<Consistency>` 다음 값 중 하나를 반환합니다.

|===
| 일관성 제어 | 설명 


 a| 
모두
 a| 
모든 노드가 데이터를 즉시 수신하거나 요청이 실패합니다.



 a| 
강함 - 글로벌
 a| 
모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 정합성을 보장합니다.



 a| 
강력한 사이트
 a| 
사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.



 a| 
읽기-후-새로-쓰기
 a| 
(기본값) 새 객체에 대한 읽기 후 쓰기 정합성을 보장하고 객체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 Amazon S3 일관성 보장 과 일치합니다.

* 참고: * 응용 프로그램이 존재하지 않는 개체에 대한 헤드 요청을 사용하는 경우 하나 이상의 스토리지 노드를 사용할 수 없는 경우 500개의 내부 서버 오류가 발생할 수 있습니다. 이러한 오류를 방지하려면 Amazon S3와 유사한 일관성 보장이 필요하지 않는 한 일관성 제어를 ""사용 가능""으로 설정합니다.



 a| 
사용 가능(헤드 작업의 최종 일관성)
 a| 
"새 쓰기 후 다시 쓰기" 정합성 수준과 동일하게 동작하지만 헤드 작업에 대한 최종 정합성 보장만 제공합니다. 스토리지 노드를 사용할 수 없는 경우 "새 쓰기 후"보다 헤드 작업에 더 높은 가용성을 제공합니다. 헤드 작업에 대한 Amazon S3 정합성 보장과 다릅니다.

|===


=== 응답 예

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
.관련 정보
link:consistency-controls.html["일관성 제어"]



== 버킷 정합성 보장 요청을 배치합니다

PUT 버킷 정합성 보장 요청을 사용하면 버킷에서 수행된 작업에 적용할 정합성 수준을 지정할 수 있습니다.

기본 정합성 보장 컨트롤은 새로 생성된 객체에 대해 읽기/쓰기 작업을 보장하도록 설정됩니다.

이 작업을 완료하려면 S3:PutBucketConsistency 권한이 있거나 계정 루트여야 합니다.



=== 요청하십시오

를 클릭합니다 `x-ntap-sg-consistency` 매개 변수는 다음 값 중 하나를 포함해야 합니다.

|===
| 일관성 제어 | 설명 


 a| 
모두
 a| 
모든 노드가 데이터를 즉시 수신하거나 요청이 실패합니다.



 a| 
강함 - 글로벌
 a| 
모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 정합성을 보장합니다.



 a| 
강력한 사이트
 a| 
사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.



 a| 
읽기-후-새로-쓰기
 a| 
(기본값) 새 객체에 대한 읽기 후 쓰기 정합성을 보장하고 객체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 Amazon S3 일관성 보장 과 일치합니다.

* 참고: * 응용 프로그램이 존재하지 않는 개체에 대한 헤드 요청을 사용하는 경우 하나 이상의 스토리지 노드를 사용할 수 없는 경우 500개의 내부 서버 오류가 발생할 수 있습니다. 이러한 오류를 방지하려면 Amazon S3와 유사한 일관성 보장이 필요하지 않는 한 일관성 제어를 ""사용 가능""으로 설정합니다.



 a| 
사용 가능(헤드 작업의 최종 일관성)
 a| 
"새 쓰기 후 다시 쓰기" 정합성 수준과 동일하게 동작하지만 헤드 작업에 대한 최종 정합성 보장만 제공합니다. 스토리지 노드를 사용할 수 없는 경우 "새 쓰기 후"보다 헤드 작업에 더 높은 가용성을 제공합니다. 헤드 작업에 대한 Amazon S3 정합성 보장과 다릅니다.

|===
* 참고: * 일반적으로 "새 쓰기 후" 정합성 보장 제어 값을 사용해야 합니다. 요청이 올바르게 작동하지 않는 경우 가능한 경우 응용 프로그램 클라이언트 동작을 변경합니다. 또는 클라이언트가 각 API 요청에 대한 정합성 제어를 지정하도록 구성합니다. 버킷 레벨에서만 정합성 제어를 최후의 수단으로 설정하십시오.



=== 요청 예

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-consistency=strong-global HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.관련 정보
link:consistency-controls.html["일관성 제어"]



== 버킷 최종 액세스 시간 요청 가져오기

[버킷 최종 액세스 시간 가져오기(Get Bucket Last Access Time) 요청 을 사용하면 개별 버킷에 대해 마지막 액세스 시간 업데이트가 활성화되거나 비활성화되었는지 확인할 수 있습니다.

이 작업을 완료하려면 S3:GetBucketLastAccessTime 권한이 있거나 계정 루트여야 합니다.



=== 요청 예

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-lastaccesstime HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== 응답 예

이 예에서는 버킷에 대해 마지막 액세스 시간 업데이트가 활성화되어 있음을 보여 줍니다.

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/10.3.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<LastAccessTime xmlns="http://s3.storagegrid.com/doc/2015-02-01/">enabled
</LastAccessTime>
----


== 버킷 최종 액세스 시간 요청

Put Bucket Last Access Time 요청을 사용하면 개별 버킷에 대한 마지막 액세스 시간 업데이트를 활성화하거나 비활성화할 수 있습니다. 마지막 액세스 시간 업데이트를 비활성화하면 성능이 향상되고 버전 10.3.0 이상으로 생성된 모든 버킷의 기본 설정이 됩니다.

이 작업을 완료하려면 버킷에 대한 S3:PutBuckketLastAccessTime 권한이 있거나 계정 루트여야 합니다.


NOTE: StorageGRID 버전 10.3부터는 모든 새 버킷에 대해 마지막 액세스 시간에 대한 업데이트가 기본적으로 비활성화됩니다. 이전 버전의 StorageGRID를 사용하여 만든 버킷이 있고 새 기본 동작과 일치시키려면 이전의 각 버킷에 대해 마지막 액세스 시간 업데이트를 명시적으로 비활성화해야 합니다. 테넌트 관리자의 Put Bucket Last Access Time 요청, * S3 * > * Bucket * > * Change Last Access Setting * 확인란 또는 테넌트 관리 API를 사용하여 마지막 액세스 시간에 대한 업데이트를 활성화하거나 비활성화할 수 있습니다.

버킷에 대해 마지막 액세스 시간 업데이트가 비활성화된 경우 버킷의 작업에 다음 동작이 적용됩니다.

* 객체 가져오기, 객체 ACL 가져오기, 객체 태그 지정 가져오기 및 헤드 객체 요청은 마지막 액세스 시간을 업데이트하지 않습니다. ILM(정보 수명 주기 관리) 평가를 위해 객체가 대기열에 추가되지 않습니다.
* Put Object - 메타데이터만 업데이트하는 객체 태그 지정 요청을 복사하고 배치하면 마지막 액세스 시간도 업데이트됩니다. ILM 평가를 위해 오브젝트가 대기열에 추가됩니다.
* 소스 버킷에 대해 마지막 액세스 시간에 대한 업데이트를 사용할 수 없는 경우 객체 복사 요청을 소스 버킷의 마지막 액세스 시간을 업데이트하지 않습니다. 복사된 객체는 소스 버킷에 대한 ILM 평가를 위해 대기열에 추가되지 않습니다. 그러나 대상의 경우, 개체 복사 요청은 항상 마지막 액세스 시간을 업데이트합니다. ILM 평가를 위해 개체의 복사본이 대기열에 추가됩니다.
* 완료 다중 파트 업로드 요청 마지막 액세스 시간 업데이트 완료된 객체가 ILM 평가를 위해 대기열에 추가됩니다.




=== 예를 요청하십시오

이 예제에서는 버킷의 마지막 액세스 시간을 설정합니다.

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-lastaccesstime=enabled HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
이 예제에서는 버킷의 마지막 액세스 시간을 비활성화합니다.

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-lastaccesstime=disabled HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.관련 정보
link:../tenant/index.html["테넌트 계정을 사용합니다"]



== 버킷 메타데이터 알림 구성 요청을 삭제합니다

Delete Bucket 메타데이터 알림 구성 요청을 사용하면 구성 XML을 삭제하여 개별 버킷에 대한 검색 통합 서비스를 비활성화할 수 있습니다.

이 작업을 완료하려면 버킷에 대한 S3:DeleteBucketMetadataNotification 권한이 있거나 계정 루트여야 합니다.



=== 요청 예

이 예제에서는 버킷에 대한 검색 통합 서비스를 비활성화하는 방법을 보여 줍니다.

[source, subs="specialcharacters,quotes"]
----
DELETE /test1?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 버킷 메타데이터 알림 구성 요청을 가져옵니다

Get Bucket 메타데이터 알림 구성 요청을 사용하면 개별 버킷에 대한 검색 통합을 구성하는 데 사용되는 구성 XML을 검색할 수 있습니다.

이 작업을 완료하려면 S3:GetBuckMetadataNotification 권한이 있거나 계정 루트여야 합니다.



=== 요청 예

이 요청은 이름이 인 버킷에 대한 메타데이터 알림 구성을 검색합니다 `bucket`.

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== 응답

응답 본문에는 버킷에 대한 메타데이터 알림 구성이 포함됩니다. 메타데이터 알림 구성을 사용하면 버킷이 검색 통합을 위해 구성되는 방식을 결정할 수 있습니다. 즉, 인덱싱된 개체와 해당 개체 메타데이터가 전송되는 끝점을 확인할 수 있습니다.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:_region:account-ID_:domain/_mydomain/myindex/mytype_</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
각 메타데이터 알림 구성에는 하나 이상의 규칙이 포함됩니다. 각 규칙은 적용되는 오브젝트와 StorageGRID가 오브젝트 메타데이터를 보내야 하는 대상을 지정합니다. 대상은 StorageGRID 끝점의 URN을 사용하여 지정해야 합니다.

|===
| 이름 | 설명 | 필수 요소입니다 


 a| 
MetadataNotificationConfiguration을 참조하십시오
 a| 
메타데이터 알림의 개체 및 대상을 지정하는 데 사용되는 규칙의 컨테이너 태그입니다.

하나 이상의 규칙 요소가 포함되어 있습니다.
 a| 
예



 a| 
규칙
 a| 
메타데이터를 지정된 인덱스에 추가해야 하는 개체를 식별하는 규칙의 컨테이너 태그입니다.

접두사가 겹치는 규칙은 거부됩니다.

MetadataNotificationConfiguration 요소에 포함되어 있습니다.
 a| 
예



 a| 
ID입니다
 a| 
규칙의 고유 식별자입니다.

Rule 요소에 포함되어 있습니다.
 a| 
아니요



 a| 
상태
 a| 
상태는 '활성화' 또는 '비활성화'가 될 수 있습니다. 비활성화된 규칙에 대해 어떠한 작업도 수행되지 않습니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
접두어
 a| 
접두사와 일치하는 개체는 규칙의 영향을 받으며 해당 메타데이터는 지정된 대상으로 전송됩니다.

모든 오브젝트를 일치시키려면 빈 접두사를 지정합니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
목적지
 a| 
규칙의 대상에 대한 컨테이너 태그입니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
urn
 a| 
객체 메타데이터가 전송되는 대상의 urn입니다. 다음 속성을 가진 StorageGRID 끝점의 URN이어야 합니다.

* `es` 세 번째 요소여야 합니다.
* URN은 메타데이터가 저장된 인덱스 및 형식으로 양식에 끝나야 합니다 `domain-name/myindex/mytype`.


엔드포인트는 테넌트 관리자 또는 테넌트 관리 API를 사용하여 구성됩니다. 다음과 같은 형식을 취합니다.

* `arn:aws:es:_region:account-ID_:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


구성 XML을 제출하기 전에 끝점을 구성해야 합니다. 그렇지 않으면 404 오류로 인해 구성이 실패합니다.

urn은 Destination 요소에 포함됩니다.
 a| 
예

|===


=== 응답 예

사이에 포함된 XML  `<MetadataNotificationConfiguration></MetadataNotificationConfiguration>` 태그는 버킷에 대해 검색 통합 끝점과의 통합이 어떻게 구성되어 있는지 보여줍니다. 이 예제에서는 개체 메타데이터가 라는 Elasticsearch 인덱스에 전송되고 있습니다 `current` 이름을 입력합니다 `2017` 라는 AWS 도메인에서 호스팅됩니다 `records`.

[listing]
----
HTTP/1.1 200 OK
Date: Thu, 20 Jul 2017 18:24:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/11.0.0
x-amz-request-id: 3832973499
Content-Length: 264
Content-Type: application/xml

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix>2017</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/records/current/2017</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.관련 정보
link:../tenant/index.html["테넌트 계정을 사용합니다"]



== PUT 버킷 메타데이터 알림 구성 요청

Put Bucket 메타데이터 알림 구성 요청을 사용하면 개별 버킷에 대한 검색 통합 서비스를 활성화할 수 있습니다. 요청 본문에 제공하는 메타데이터 알림 구성 XML은 대상 검색 인덱스에 메타데이터가 전송되는 개체를 지정합니다.

이 작업을 완료하려면 버킷에 대한 S3:PutBucketMetadataNotification 권한이 있거나 계정 루트여야 합니다.



=== 요청하십시오

요청 본문에는 메타데이터 알림 구성이 포함되어야 합니다. 각 메타데이터 알림 구성에는 하나 이상의 규칙이 포함됩니다. 각 규칙은 적용되는 오브젝트와 StorageGRID가 오브젝트 메타데이터를 보내야 하는 대상을 지정합니다.

개체 이름의 접두어를 기준으로 개체를 필터링할 수 있습니다. 예를 들어, 접두사가 있는 개체에 대한 메타데이터를 보낼 수 있습니다 `/images` 목적지 하나와 접두사가 있는 오브젝트 `/videos` 다른 사람에게.

중복되는 접두사가 있는 구성은 유효하지 않으며 제출될 때 거부됩니다. 예를 들어, 접두사가 있는 개체에 대해 하나의 규칙이 포함된 구성입니다 `test` 접두사가 있는 개체에 대한 두 번째 규칙입니다 `test2` 허용되지 않습니다.

대상은 StorageGRID 끝점의 URN을 사용하여 지정해야 합니다. 메타데이터 알림 구성이 제출되거나 요청이 로 실패하는 경우 엔드포인트가 있어야 합니다 `400 Bad Request`. 오류 메시지는 다음과 같습니다. `Unable to save the metadata notification (search) policy. The specified endpoint URN does not exist: _URN_.`

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
이 표에서는 메타데이터 알림 구성 XML의 요소에 대해 설명합니다.

|===
| 이름 | 설명 | 필수 요소입니다 


 a| 
MetadataNotificationConfiguration을 참조하십시오
 a| 
메타데이터 알림의 개체 및 대상을 지정하는 데 사용되는 규칙의 컨테이너 태그입니다.

하나 이상의 규칙 요소가 포함되어 있습니다.
 a| 
예



 a| 
규칙
 a| 
메타데이터를 지정된 인덱스에 추가해야 하는 개체를 식별하는 규칙의 컨테이너 태그입니다.

접두사가 겹치는 규칙은 거부됩니다.

MetadataNotificationConfiguration 요소에 포함되어 있습니다.
 a| 
예



 a| 
ID입니다
 a| 
규칙의 고유 식별자입니다.

Rule 요소에 포함되어 있습니다.
 a| 
아니요



 a| 
상태
 a| 
상태는 '활성화' 또는 '비활성화'가 될 수 있습니다. 비활성화된 규칙에 대해 어떠한 작업도 수행되지 않습니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
접두어
 a| 
접두사와 일치하는 개체는 규칙의 영향을 받으며 해당 메타데이터는 지정된 대상으로 전송됩니다.

모든 오브젝트를 일치시키려면 빈 접두사를 지정합니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
목적지
 a| 
규칙의 대상에 대한 컨테이너 태그입니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
urn
 a| 
객체 메타데이터가 전송되는 대상의 urn입니다. 다음 속성을 가진 StorageGRID 끝점의 URN이어야 합니다.

* `es` 세 번째 요소여야 합니다.
* URN은 메타데이터가 저장된 인덱스 및 형식으로 양식에 끝나야 합니다 `domain-name/myindex/mytype`.


엔드포인트는 테넌트 관리자 또는 테넌트 관리 API를 사용하여 구성됩니다. 다음과 같은 형식을 취합니다.

* `arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


구성 XML을 제출하기 전에 끝점을 구성해야 합니다. 그렇지 않으면 404 오류로 인해 구성이 실패합니다.

urn은 Destination 요소에 포함됩니다.
 a| 
예

|===


=== 예를 요청하십시오

이 예제에서는 버킷에 대한 검색 통합을 활성화하는 방법을 보여 줍니다. 이 예제에서 모든 오브젝트의 오브젝트 메타데이터는 동일한 대상으로 전송됩니다.

[source, subs="specialcharacters,quotes"]
----
PUT /test1?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix></Prefix>
        <Destination>
           <Urn>urn:sgws:es:::sgws-notifications/test1/all</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
이 예제에서는 접두사와 일치하는 개체의 개체 메타데이터를 보여 줍니다 `/images` 은(는) 한 대상으로 전송되지만 접두사와 일치하는 오브젝트의 오브젝트 메타데이터는 전송됩니다 `/videos` 두 번째 대상으로 전송됩니다.

[source, subs="specialcharacters,quotes"]
----
PUT /graphics?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Images-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/images</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/es-domain/graphics/imagetype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Videos-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/videos</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-west-1:22222222:domain/es-domain/graphics/videotype</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.관련 정보
link:../tenant/index.html["테넌트 계정을 사용합니다"]



=== JSON이 검색 통합 서비스에 의해 생성되었습니다

버킷에 대한 검색 통합 서비스를 활성화하면 개체 메타데이터 또는 태그를 추가, 업데이트 또는 삭제할 때마다 JSON 문서가 생성되어 대상 끝점으로 전송됩니다.

이 예제에서는 키가 있는 개체가 생성될 수 있는 JSON의 예를 보여 줍니다 `SGWS/Tagging.txt` 이(가) 라는 이름의 버킷에 생성됩니다 `test`. 를 클릭합니다 `test` 버킷의 버전이 지정되지 않으므로 이(가) 이(가) 필요합니다 `versionId` 태그가 비어 있습니다.

[listing]
----
{
  "bucket": "test",
  "key": "SGWS/Tagging.txt",
  "versionId": "",
  "accountId": "86928401983529626822",
  "size": 38,
  "md5": "3d6c7634a85436eee06d43415012855",
  "region":"us-east-1"
  "metadata": {
    "age": "25"
  },
  "tags": {
    "color": "yellow"
  }
}
----


=== 메타데이터 알림에 포함된 개체 메타데이터입니다

이 표에는 검색 통합이 활성화된 경우 대상 끝점으로 전송되는 JSON 문서에 포함된 모든 필드가 나열됩니다.

문서 이름에는 버킷 이름, 오브젝트 이름 및 버전 ID(있는 경우)가 포함됩니다.

|===
| 유형 | 항목 이름 | 설명 


 a| 
버킷 및 오브젝트 정보
 a| 
버킷
 a| 
버킷의 이름입니다



 a| 
버킷 및 오브젝트 정보
 a| 
키
 a| 
개체 키 이름입니다



 a| 
버킷 및 오브젝트 정보
 a| 
버전 ID
 a| 
오브젝트 버전, 버전 버킷 내 오브젝트



 a| 
버킷 및 오브젝트 정보
 a| 
지역
 a| 
버킷 영역(예 `us-east-1`



 a| 
시스템 메타데이터
 a| 
크기
 a| 
HTTP 클라이언트에 표시되는 개체 크기(바이트)입니다



 a| 
시스템 메타데이터
 a| 
MD5
 a| 
개체 해시



 a| 
사용자 메타데이터
 a| 
메타데이터
`_key:value_`
 a| 
객체에 대한 모든 사용자 메타데이터를 키 값 쌍으로 사용합니다



 a| 
태그
 a| 
태그
`_key:value_`
 a| 
개체에 대해 정의된 모든 개체 태그를 키 값 쌍으로 사용합니다

|===
* 참고: * 태그 및 사용자 메타데이터의 경우 StorageGRID는 날짜 및 숫자를 Elasticsearch에 문자열로 전달하거나 S3 이벤트 알림으로 전달합니다. 이러한 문자열을 날짜 또는 숫자로 해석하도록 Elasticsearch를 구성하려면 동적 필드 매핑 및 날짜 형식 매핑에 대한 Elasticsearch 지침을 따르십시오. 검색 통합 서비스를 구성하기 전에 인덱스에서 동적 필드 매핑을 활성화해야 합니다. 문서가 인덱싱된 후에는 인덱스에서 문서의 필드 형식을 편집할 수 없습니다.



== 스토리지 사용 요청 가져오기

Get Storage Usage 요청은 계정이 사용하는 총 스토리지 양과 계정과 연결된 각 버킷에 대해 알려줍니다.

계정 및 해당 버킷에서 사용되는 스토리지의 양은 을 사용하여 수정된 Get Service 요청을 통해 얻을 수 있습니다 `x-ntap-sg-usage` 쿼리 매개 변수입니다. 시스템에서 처리하는 PUT 및 삭제 요청과는 별도로 버킷 스토리지 사용량을 추적합니다. 특히 시스템이 과부하 상태인 경우, 사용 값이 요청 처리를 기준으로 예상 값과 일치하기 전에 약간의 지연이 있을 수 있습니다.

기본적으로 StorageGRID는 강력한 글로벌 일관성을 사용하여 사용 정보 검색을 시도합니다. 강력한 글로벌 일관성을 달성할 수 없는 경우 StorageGRID는 강력한 사이트 일관성으로 사용 정보를 검색합니다.

이 작업을 완료하려면 S3:ListAllMyBucket 권한이 있거나 계정 루트여야 합니다.



=== 요청 예

[source, subs="specialcharacters,quotes"]
----
GET /?x-ntap-sg-usage HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== 응답 예

이 예에서는 두 버킷에 4개의 오브젝트와 12바이트의 데이터가 있는 계정을 보여 줍니다. 각 버킷에는 2개의 오브젝트와 6바이트의 데이터가 포함되어 있습니다.

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 00:49:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/10.2.0
x-amz-request-id: 727237123
Content-Length: 427
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<UsageResult xmlns="http://s3.storagegrid.com/doc/2015-02-01">
<CalculationTime>2014-11-19T05:30:11.000000Z</CalculationTime>
<ObjectCount>4</ObjectCount>
<DataBytes>12</DataBytes>
<Buckets>
<Bucket>
<Name>bucket1</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
<Bucket>
<Name>bucket2</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
</Buckets>
</UsageResult>
----


=== 버전 관리

저장된 모든 개체 버전은 에 기여합니다 `ObjectCount` 및 `DataBytes` 응답의 값입니다. Delete markers(마커 삭제)는 에 추가되지 않습니다 `ObjectCount` 합계.

.관련 정보
link:consistency-controls.html["일관성 제어"]



== 레거시 규정 준수를 위한 더 이상 사용되지 않는 버킷 요청

StorageGRID S3 REST API를 사용하여 레거시 규정 준수 기능을 사용하여 생성된 버킷을 관리해야 할 수 있습니다.



=== 규정 준수 기능이 사용되지 않습니다

이전 StorageGRID 버전에서 사용할 수 있었던 StorageGRID 규정 준수 기능은 더 이상 사용되지 않으며 S3 오브젝트 잠금으로 대체되었습니다.

이전에 글로벌 규정 준수 설정을 활성화한 경우 StorageGRID 11.5로 업그레이드하면 글로벌 S3 오브젝트 잠금 설정이 자동으로 활성화됩니다. Compliance를 사용하도록 설정한 상태에서 새 버킷을 더 이상 생성할 수 없지만, 필요에 따라 StorageGRID S3 REST API를 사용하여 기존의 규정을 준수하는 버킷을 관리할 수 있습니다.

link:s3-rest-api-supported-operations-and-limitations.html["S3 오브젝트 잠금 사용"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

https://["NetApp 기술 자료: StorageGRID 11.5에서 레거시 준수 버킷을 관리하는 방법"]



=== 사용되지 않음: 규정 준수를 위해 버킷 요청 수정을 배치합니다

SGCompliance XML 요소는 사용되지 않습니다. 이전 버전에서는 이 StorageGRID 사용자 정의 요소를 PUT 버킷 요청의 선택적 XML 요청 본문에 포함하여 준수 버킷을 생성할 수 있었습니다.


IMPORTANT: 이전 StorageGRID 버전에서 사용할 수 있었던 StorageGRID 규정 준수 기능은 더 이상 사용되지 않으며 S3 오브젝트 잠금으로 대체되었습니다.

link:s3-rest-api-supported-operations-and-limitations.html["S3 오브젝트 잠금 사용"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

https://["NetApp 기술 자료: StorageGRID 11.5에서 레거시 준수 버킷을 관리하는 방법"]

Compliance가 설정된 새 버킷을 더 이상 생성할 수 없습니다. 새 준수 버킷을 생성하기 위해 준수 준수를 위해 Put Bucket 요청 수정을 사용하려는 경우 다음 오류 메시지가 반환됩니다.

[listing]
----
The Compliance feature is deprecated.
Contact your StorageGRID administrator if you need to create new Compliant buckets.
----
.관련 정보
link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

link:../tenant/index.html["테넌트 계정을 사용합니다"]



=== 사용되지 않음: 버킷 준수 요청 가져오기

Get Bucket 준수 요청은 더 이상 사용되지 않습니다. 그러나 이 요청을 계속 사용하여 기존 레거시 준수 버킷에 현재 적용되는 준수 설정을 확인할 수 있습니다.


IMPORTANT: 이전 StorageGRID 버전에서 사용할 수 있었던 StorageGRID 규정 준수 기능은 더 이상 사용되지 않으며 S3 오브젝트 잠금으로 대체되었습니다.

link:s3-rest-api-supported-operations-and-limitations.html["S3 오브젝트 잠금 사용"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

https://["NetApp 기술 자료: StorageGRID 11.5에서 레거시 준수 버킷을 관리하는 방법"]

이 작업을 완료하려면 S3:GetBucketCompliance 권한이 있거나 계정 루트여야 합니다.



==== 요청 예

이 요청 예제를 통해 이름이 인 버킷의 준수 설정을 확인할 수 있습니다 `mybucket`.

[source, subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


==== 응답 예

응답 XML에서 `<SGCompliance>` 에는 버킷에 적용되는 준수 설정이 나와 있습니다. 이 예제 응답에서는 오브젝트를 그리드에 인제스트하는 시점을 시작으로 각 오브젝트를 1년(525,600분)동안 보존할 버킷의 규정 준수 설정을 보여 줍니다. 현재 이 버킷에 대한 법적 보류가 없습니다. 각 개체는 1년 후에 자동으로 삭제됩니다.

[source, subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
|===
| 이름 | 설명 


 a| 
RetenionPeriodMinutes(주기적 지연 시간)
 a| 
이 버킷에 추가된 객체의 보존 기간(분)입니다. 보존 기간은 객체가 그리드에 수집될 때 시작됩니다.



 a| 
LegalHold
 a| 
* 참: 이 버킷은 현재 법적 증거 자료 보관 중입니다. 이 버킷의 오브젝트는 보존 기간이 만료된 경우에도 법적 보류가 해제될 때까지 삭제할 수 없습니다.
* 거짓: 이 버킷은 현재 법적 증거 자료 보관 중이 아닙니다. 이 버킷의 오브젝트는 보존 기간이 만료되면 삭제할 수 있습니다.




 a| 
자동 삭제
 a| 
* 참: 버킷이 법적 보존 상태에 있지 않는 한, 보존 기간이 만료되면 이 버킷의 객체가 자동으로 삭제됩니다.
* False: 보존 기간이 만료되면 이 버킷의 객체가 자동으로 삭제되지 않습니다. 이러한 개체를 삭제하려면 해당 개체를 수동으로 삭제해야 합니다.


|===


==== 오류 응답

버킷이 규정을 준수하도록 생성되지 않은 경우 응답에 대한 HTTP 상태 코드는 입니다 `404 Not Found`, 의 S3 오류 코드 포함 `XNoSuchBucketCompliance`.

.관련 정보
link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

link:../tenant/index.html["테넌트 계정을 사용합니다"]



=== 폐기됨: 버킷 준수 요청을 넣으십시오

PUT 버킷 준수 요청은 더 이상 사용되지 않습니다. 그러나 이 요청을 계속 사용하여 기존 레거시 준수 버킷의 준수 설정을 수정할 수 있습니다. 예를 들어, 기존 버킷을 법적 보존 상태로 놓거나 보존 기간을 늘릴 수 있습니다.


IMPORTANT: 이전 StorageGRID 버전에서 사용할 수 있었던 StorageGRID 규정 준수 기능은 더 이상 사용되지 않으며 S3 오브젝트 잠금으로 대체되었습니다.

link:s3-rest-api-supported-operations-and-limitations.html["S3 오브젝트 잠금 사용"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

https://["NetApp 기술 자료: StorageGRID 11.5에서 레거시 준수 버킷을 관리하는 방법"]

이 작업을 완료하려면 S3:PutBucketCompliance 권한이 있거나 계정 루트 권한이 있어야 합니다.

PUT 버킷 준수 요청을 발행할 때 준수 설정의 모든 필드에 값을 지정해야 합니다.



==== 요청 예

이 예제 요청은 이름이 인 버킷의 준수 설정을 수정합니다 `mybucket`. 이 예제에서는 의 개체를 보여 줍니다 `mybucket` 이제 오브젝트를 그리드로 인제스트하는 시점을 시작으로 1년이 아닌 2년(1,051,200분) 동안 보존됩니다. 이 버킷에는 법적 구속이 없습니다. 각 개체는 2년 후에 자동으로 삭제됩니다.

[source, subs="specialcharacters,quotes"]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization name_
Host: _host_
Content-Length: 152

<SGCompliance>
  <RetentionPeriodMinutes>1051200</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
|===
| 이름 | 설명 


 a| 
RetenionPeriodMinutes(주기적 지연 시간)
 a| 
이 버킷에 추가된 객체의 보존 기간(분)입니다. 보존 기간은 객체가 그리드에 수집될 때 시작됩니다.

* 주의: * RetenitionPeriodMinutes에 새 값을 지정할 때는 버킷의 현재 보존 기간과 같거나 큰 값을 지정해야 합니다. 버킷의 보존 기간이 설정된 후에는 해당 값을 줄일 수 없으며 증가만 가능합니다.



 a| 
LegalHold
 a| 
* 참: 이 버킷은 현재 법적 증거 자료 보관 중입니다. 이 버킷의 오브젝트는 보존 기간이 만료된 경우에도 법적 보류가 해제될 때까지 삭제할 수 없습니다.
* 거짓: 이 버킷은 현재 법적 증거 자료 보관 중이 아닙니다. 이 버킷의 오브젝트는 보존 기간이 만료되면 삭제할 수 있습니다.




 a| 
자동 삭제
 a| 
* 참: 버킷이 법적 보존 상태에 있지 않는 한, 보존 기간이 만료되면 이 버킷의 객체가 자동으로 삭제됩니다.
* False: 보존 기간이 만료되면 이 버킷의 객체가 자동으로 삭제되지 않습니다. 이러한 개체를 삭제하려면 해당 개체를 수동으로 삭제해야 합니다.


|===


==== 규정 준수 설정을 위한 정합성 보장 레벨

PUT 버킷 준수 요청으로 S3 버킷의 준수 설정을 업데이트하면 StorageGRID는 그리드 전체에서 버킷의 메타데이터를 업데이트하려고 시도합니다. 기본적으로 StorageGRID는 * strong-global * 일관성 수준을 사용하여 버킷 메타데이터를 포함하는 모든 데이터 센터 사이트와 모든 스토리지 노드가 변경된 규정 준수 설정에 대해 읽기-쓰기 후 일관성을 유지하도록 보장합니다.

데이터 센터 사이트 또는 사이트의 여러 스토리지 노드를 사용할 수 없기 때문에 StorageGRID가 * 강력한 글로벌 * 정합성 보장 수준을 달성할 수 없는 경우 응답에 대한 HTTP 상태 코드는 입니다 `503 Service Unavailable.`

이 응답을 받으면 그리드 관리자에게 문의하여 필요한 스토리지 서비스를 가능한 빨리 사용할 수 있도록 해야 합니다. 그리드 관리자가 각 사이트에서 충분한 스토리지 노드를 사용할 수 없는 경우, 기술 지원 부서에서 * strong-site * 정합성 보장 수준을 강제로 진행하여 실패한 요청을 다시 시도하도록 할 수 있습니다.


IMPORTANT: 기술 지원 부서의 지시가 있는 경우를 제외하고, 이 레벨을 사용할 경우 발생할 수 있는 결과를 이해하지 않는 한 * 강력한 사이트 * 일관성 수준을 강제로 버킷 규정 준수를 강제하지 마십시오.

정합성 보장 수준을 * strong-site * 로 축소하면 StorageGRID는 업데이트된 규정 준수 설정이 사이트 내의 클라이언트 요청에 대해서만 읽기/쓰기 후 일관성을 갖게 됩니다. 즉, 모든 사이트 및 스토리지 노드를 사용할 수 있을 때까지 StorageGRID 시스템에 이 버킷에 대한 여러 개의 일관되지 않은 설정이 일시적으로 있을 수 있습니다. 설정이 일치하지 않으면 예기치 않거나 원치 않는 동작이 발생할 수 있습니다. 예를 들어, 버킷을 법적 증거 자료 보관 아래에 놓고 정합성 보장 수준을 낮추면 버킷의 이전 규정 준수 설정(즉, 법적 증거 자료 보관)이 일부 데이터 센터 사이트에서 계속 적용될 수 있습니다. 따라서 보존 기간이 만료되면 사용자나 자동 삭제(활성화된 경우)에 의해 법적 보류라고 생각하는 개체가 삭제될 수 있습니다.

strong-site * 정합성 보장 레벨을 강제로 사용하려면 Put Bucket 준수 요청을 다시 발행하고 을 포함합니다 `Consistency-Control` HTTP 요청 헤더는 다음과 같습니다.

[listing]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Consistency-Control: strong-site
----


==== 오류 응답

* 버킷이 규정을 준수하도록 생성되지 않은 경우 응답에 대한 HTTP 상태 코드는 입니다 `404 Not Found`.
* If(경우 `RetentionPeriodMinutes` 요청이 버킷의 현재 보존 기간보다 작은 경우 HTTP 상태 코드는 입니다 `400 Bad Request`.


.관련 정보
link:storagegrid-s3-rest-api-operations.html["사용되지 않음: 규정 준수를 위해 버킷 요청 수정을 배치합니다"]

link:../tenant/index.html["테넌트 계정을 사용합니다"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]
