---
permalink: monitor/generating-text-reports.html 
sidebar: sidebar 
keywords: reports, text 
summary: 텍스트 보고서는 NMS 서비스에서 처리한 속성 데이터 값의 텍스트 표현을 표시합니다. 데이터 센터 사이트, 그리드 노드, 구성 요소 또는 서비스에 대해 보고할 수 있습니다. 
---
= 텍스트 보고서를 생성하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
텍스트 보고서는 NMS 서비스에서 처리한 속성 데이터 값의 텍스트 표현을 표시합니다. 데이터 센터 사이트, 그리드 노드, 구성 요소 또는 서비스에 대해 보고할 수 있습니다.

.필요한 것
* 지원되는 브라우저를 사용하여 Grid Manager에 로그인해야 합니다.
* 특정 액세스 권한이 있어야 합니다.


.이 작업에 대해
지속적으로 변경해야 하는 특성 데이터의 경우 NMS 서비스(소스에서)가 정기적으로 이 특성 데이터를 샘플링합니다. 자주 변경되지 않는 특성 데이터(예: 상태 또는 상태 변경 등의 이벤트 기반 데이터)의 경우 값이 변경되면 특성 값이 NMS 서비스로 전송됩니다.

표시되는 보고서 유형은 구성된 기간에 따라 다릅니다. 기본적으로 집계 텍스트 보고서는 1주 이상의 기간 동안 생성됩니다.

회색 텍스트는 서비스가 샘플링되는 동안 관리적으로 중단되었음을 나타냅니다. 파란색 텍스트는 서비스가 알 수 없는 상태임을 나타냅니다.

.단계
. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
. grid node_ * > * _component 또는 service_ * > * Reports * > * Text * 를 선택합니다.
. 특성 * 드롭다운 목록에서 보고할 특성을 선택합니다.
. 페이지당 결과 수 * 드롭다운 목록에서 페이지당 결과 수를 선택합니다.
. 값을 최대 3자리(예: 비율로 보고된 속성)로 반올림하려면 * 원시 데이터 * 확인란의 선택을 취소합니다.
. 빠른 쿼리 * 드롭다운 목록에서 보고할 기간을 선택합니다.
+
사용자 지정 쿼리 옵션을 선택하여 특정 시간 범위를 선택합니다.

+
잠시 후에 보고서가 나타납니다. 긴 시간 범위의 표 형성을 위해 몇 분 정도 기다립니다.

. 사용자 지정 쿼리를 선택한 경우 * 시작일 * 및 * 종료일 * 을 입력하여 보고할 기간을 사용자 지정해야 합니다.
+
형식을 사용합니다 `YYYY/MM/DDHH:MM:SS` 현지 시간. 형식과 일치시키려면 맨 앞에 0이 있어야 합니다. 예를 들어, 2017/4/6 7:30:00은 검증에 실패합니다. 올바른 형식은 2017/04/06 07:30:00입니다.

. Update * 를 클릭합니다.
+
몇 분 후에 텍스트 보고서가 생성됩니다. 긴 시간 범위의 표 형성을 위해 몇 분 정도 기다립니다. 쿼리에 대해 설정된 시간에 따라 원시 텍스트 보고서 또는 집계 텍스트 보고서가 표시됩니다.

. 보고서를 인쇄하려면 마우스 오른쪽 단추로 클릭하고 * 인쇄 * 를 선택한 다음 필요한 프린터 설정을 수정하고 * 인쇄 * 를 클릭합니다.

