---
permalink: monitor/generating-charts.html 
sidebar: sidebar 
keywords: charts, generating 
summary: 차트는 특성 데이터 값의 그래픽 표현을 표시합니다. 데이터 센터 사이트, 그리드 노드, 구성 요소 또는 서비스에 대해 보고할 수 있습니다. 
---
= 차트 생성 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
차트는 특성 데이터 값의 그래픽 표현을 표시합니다. 데이터 센터 사이트, 그리드 노드, 구성 요소 또는 서비스에 대해 보고할 수 있습니다.

.필요한 것
* 지원되는 브라우저를 사용하여 Grid Manager에 로그인해야 합니다.
* 특정 액세스 권한이 있어야 합니다.


.단계
. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
. grid node_ * > * _component 또는 service_ * > * Reports * > * Charts * 를 선택합니다.
. 특성 * 드롭다운 목록에서 보고할 특성을 선택합니다.
. Y축을 0에서 시작하려면 * 수직 배율 * 확인란을 선택 취소합니다.
. 값을 전체 정밀도로 표시하려면 * Raw Data * 확인란을 선택하거나 값을 최대 3개의 소수 자릿수(예: 비율로 보고된 속성)로 반올림하려면 * Raw Data * 확인란을 선택 취소합니다.
. 빠른 쿼리 * 드롭다운 목록에서 보고할 기간을 선택합니다.
+
사용자 지정 쿼리 옵션을 선택하여 특정 시간 범위를 선택합니다.

+
잠시 후에 차트가 나타납니다. 긴 시간 범위의 표 형성을 위해 몇 분 정도 기다립니다.

. 사용자 지정 쿼리를 선택한 경우 * 시작 날짜 * 와 * 종료 날짜 * 를 입력하여 차트의 기간을 사용자 지정합니다.
+
형식을 사용합니다 `_YYYY/MM/DDHH:MM:SS_` 현지 시간. 형식과 일치시키려면 맨 앞에 0이 있어야 합니다. 예를 들어, 2017/4/6 7:30:00은 검증에 실패합니다. 올바른 형식은 2017/04/06 07:30:00입니다.

. Update * 를 클릭합니다.
+
차트가 몇 분 후에 생성됩니다. 긴 시간 범위의 표 형성을 위해 몇 분 정도 기다립니다. 쿼리에 대해 설정된 시간에 따라 원시 텍스트 보고서 또는 집계 텍스트 보고서가 표시됩니다.

. 차트를 인쇄하려면 마우스 오른쪽 단추를 클릭하고 * 인쇄 * 를 선택한 다음 필요한 프린터 설정을 수정하고 * 인쇄 * 를 클릭합니다.

