---
permalink: monitor/managing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: managing, alarms, alerts 
summary: StorageGRID 경고 시스템은 주의가 필요한 운영 문제를 알려주도록 설계되었습니다. 필요에 따라 레거시 알람 시스템을 사용하여 시스템을 모니터링할 수도 있습니다. 
---
= 경고 및 알람 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 경고 시스템은 주의가 필요한 운영 문제를 알려주도록 설계되었습니다. 필요에 따라 레거시 알람 시스템을 사용하여 시스템을 모니터링할 수도 있습니다. 이 섹션에는 다음과 같은 하위 섹션이 포함되어 있습니다.

* link:comparing-alerts-and-alarms.html["경고 및 알람 비교"]
* link:managing-alerts.html["알림 관리"]
* link:managing-alarms.html["알람 관리(기존 시스템)"]


StorageGRID에는 문제에 대한 정보를 제공하는 두 개의 시스템이 있습니다.



== 경고 시스템

경고 시스템은 StorageGRID 시스템에서 발생할 수 있는 문제를 모니터링하는 기본 도구로 설계되었습니다. 경고 시스템은 문제 감지, 평가 및 해결을 위한 사용이 간편한 인터페이스를 제공합니다.

알림은 알림 규칙 조건이 true로 평가될 때 특정 심각도 수준에서 트리거됩니다. 경고가 트리거되면 다음 작업이 수행됩니다.

* 그리드 관리자의 대시보드에 경고 심각도 아이콘이 표시되고 현재 경고의 수가 증가합니다.
* 이 경고는 * 노드 * > *_노드_ * > * 개요 * 탭에 표시됩니다.
* SMTP 서버를 구성하고 수신자에 대한 이메일 주소를 제공한 경우 이메일 알림이 전송됩니다.
* StorageGRID SNMP 에이전트를 구성한 경우 SNMP(Simple Network Management Protocol) 알림이 전송됩니다.




== 레거시 알람 시스템

알람 시스템은 지원되지만 레거시 시스템으로 간주됩니다. 경고와 마찬가지로, 속성은 정의된 임계값에 도달할 때 특정 심각도 수준에서 트리거됩니다. 그러나 알림과 달리, 많은 알람은 사용자가 안전하게 무시할 수 있는 이벤트에 대해 트리거되며, 이로 인해 e-메일 또는 SNMP 알림이 과도하게 많아질 수 있습니다.

알람이 트리거되면 다음과 같은 동작이 발생합니다.

* 대시보드의 레거시 알람 수가 증가합니다.
* 알람은 * Support * > * Alarms (Legacy) * > * Current Alarms * (현재 알람) 페이지에 나타납니다.
* SMTP 서버를 구성하고 하나 이상의 메일 그룹을 구성한 경우 이메일 알림이 전송됩니다.
* StorageGRID SNMP 에이전트를 구성한 경우 SNMP 알림이 전송될 수 있습니다. (모든 알람 또는 알람 심각도에 대해 SNMP 알림이 전송되지 않습니다.)

