---
permalink: monitor/monitoring-events.html 
sidebar: sidebar 
keywords: monitor, monitoring events, events, storageGRID events 
summary: syslog 서버에 기록된 이벤트를 추적하기 위해 만든 사용자 지정 이벤트를 포함하여 그리드 노드에서 감지한 이벤트를 모니터링할 수 있습니다. 가장 최근의 이벤트에 대한 자세한 내용은 그리드 관리자에 표시된 마지막 이벤트 메시지를 참조하십시오. 
---
= 이벤트 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
syslog 서버에 기록된 이벤트를 추적하기 위해 만든 사용자 지정 이벤트를 포함하여 그리드 노드에서 감지한 이벤트를 모니터링할 수 있습니다. 가장 최근의 이벤트에 대한 자세한 내용은 그리드 관리자에 표시된 마지막 이벤트 메시지를 참조하십시오.

이벤트 메시지는 에도 나열됩니다 `/var/local/log/bycast-err.log` 로그 파일.

SMTT(Total events) 알람은 네트워크 문제, 정전 또는 업그레이드와 같은 문제로 인해 반복적으로 발생할 수 있습니다. 이 섹션에서는 이러한 알람이 발생한 이유를 보다 잘 이해할 수 있도록 이벤트 조사에 대한 정보를 제공합니다. 알려진 문제로 인해 이벤트가 발생한 경우 이벤트 카운터를 다시 설정하는 것이 안전합니다.



== 노드 페이지에서 이벤트 검토

노드 페이지에는 각 그리드 노드에 대한 시스템 이벤트가 나열됩니다.

. 노드 * 를 선택합니다.
. grid node_ * > * Events * 를 선택합니다.
. 페이지 맨 위에서 그리드 노드에서 감지한 마지막 이벤트를 설명하는 * Last Event * 에 대한 이벤트가 표시되는지 확인합니다.
+
이벤트는 그리드 노드에서 verbatim으로 전달되며 심각도 수준의 오류 또는 중요 로그 메시지를 포함합니다.

. 이벤트 또는 오류의 개수가 0이 아닌 경우 표를 검토하십시오.
. 문제를 해결한 후 * Reset event counts * (이벤트 카운트 재설정 *)를 클릭하여 카운트를 0으로 되돌립니다.




== 그리드 토폴로지 페이지에서 이벤트 검토

그리드 토폴로지 페이지에는 각 그리드 노드에 대한 시스템 이벤트도 나열됩니다.

. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
. site_ * > *_GRID node_ * > * SSM * > * Events * > * Overview * > * Main * 을 선택합니다.


.관련 정보
link:resetting-event-counts.html["이벤트 수를 재설정하는 중입니다"]

link:../monitor/logs-files-reference.html["로그 파일 참조"]
