---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 노드의 명령 셸에서 그리드 노드를 종료할 수 있습니다. 
---
= 그리드 노드 종료
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드의 명령 셸에서 그리드 노드를 종료할 수 있습니다.

.필요한 것
* 에 가 있어야 합니다 `Passwords.txt` 파일.


.이 작업에 대해
이 절차를 수행하기 전에 다음 사항을 검토하십시오.

* 일반적으로 중단을 방지하기 위해 노드를 한 번에 두 개 이상 종료해서는 안 됩니다.
* 설명서나 기술 지원 부서에서 명시적으로 지시하지 않는 한 유지보수 절차 중에 노드를 종료하지 마십시오.
* 종료 프로세스는 노드가 설치되는 위치를 기반으로 다음과 같이 진행됩니다.
+
** VMware 노드를 종료하면 가상 머신이 종료됩니다.
** Linux 노드를 종료하면 컨테이너가 종료됩니다.
** StorageGRID 어플라이언스 노드를 종료하면 컴퓨팅 컨트롤러가 종료됩니다.


* 스토리지 노드를 종료할 계획인 경우 다음 사항에 유의하십시오.
+
** ILM 규칙이 이중 커밋의 수집 동작을 지정하거나 규칙이 Balanced 를 지정하며 필요한 모든 복사본을 즉시 생성할 수 없는 경우, StorageGRID는 새로 수집된 개체를 즉시 동일한 사이트의 두 스토리지 노드에 커밋하고 나중에 ILM을 평가합니다. 특정 사이트에서 두 개 이상의 스토리지 노드를 종료하려면 종료 기간 동안 해당 개체에 액세스하지 못할 수도 있습니다.
** 스토리지 노드가 종료될 때 모든 개체에 액세스할 수 있도록 하려면 노드를 종료하기 전에 약 1시간 동안 사이트에서 오브젝트 인제스트를 중지하십시오.




.단계
. 그리드 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
.. 루트로 전환하려면 다음 명령을 입력합니다. `su -`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.


+
루트로 로그인하면 프롬프트가 에서 변경됩니다 `$` 를 선택합니다 `#`.

. 모든 서비스 중지: `service servermanager stop`
+
서비스를 종료하는 데 최대 15분이 걸릴 수 있으며, 종료 프로세스를 모니터링하기 위해 시스템에 원격으로 로그인하기를 원할 수 있습니다.

. 명령 셸에서 로그아웃합니다. `exit`


시스템을 종료한 후 그리드 노드의 전원을 끌 수 있습니다.

link:powering-down-host.html["호스트 전원을 끕니다"]

.관련 정보
link:../admin/index.html["StorageGRID 관리"]
