---
permalink: primer/tabs-for-nodes-page.html 
sidebar: sidebar 
keywords: nodes page, hardware tab, network tab, storage tab, events tab, objects tab, ilm tab, load balancer tab, platform services tab, santricity system manager tab 
summary: 노드 페이지 맨 위의 탭은 왼쪽의 트리에서 선택한 항목을 기반으로 합니다. 
---
= 노드 페이지의 탭입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 페이지 맨 위의 탭은 왼쪽의 트리에서 선택한 항목을 기반으로 합니다.

[cols="1a,2a,1a"]
|===
| 탭 이름 | 설명 | 에 포함 


 a| 
개요
 a| 
* 각 노드에 대한 기본 정보를 제공합니다.
* 노드에 영향을 미치는 현재, 확인되지 않은 알람을 표시합니다.

 a| 
모든 노드



 a| 
하드웨어
 a| 
* 각 노드의 CPU 사용률 및 메모리 사용량을 표시합니다
* 어플라이언스 노드의 경우 에 추가 하드웨어 정보가 나와 있습니다.

 a| 
모든 노드



 a| 
네트워크
 a| 
네트워크 인터페이스를 통해 수신 및 전송된 네트워크 트래픽을 보여 주는 그래프를 표시합니다.
 a| 
모든 노드, 각 사이트 및 전체 그리드



 a| 
스토리지
 a| 
* 각 노드의 디스크 디바이스 및 볼륨에 대한 자세한 내용은 에 나와 있습니다.
* 스토리지 노드, 각 사이트 및 전체 그리드에는 시간에 따라 사용된 오브젝트 데이터 스토리지 및 메타데이터 스토리지를 보여 주는 그래프가 포함됩니다.

 a| 
모든 노드, 각 사이트 및 전체 그리드



 a| 
이벤트
 a| 
네트워크 오류와 같은 오류를 포함하여 시스템 오류 또는 오류 이벤트의 수를 표시합니다.
 a| 
모든 노드



 a| 
오브젝트
 a| 
* S3, Swift 수집 및 검색 속도에 대한 정보를 제공합니다.
* 스토리지 노드의 경우 메타데이터 저장소 쿼리 및 백그라운드 확인에 대한 개체 수와 정보를 제공합니다.

 a| 
스토리지 노드, 각 사이트 및 전체 그리드



 a| 
ILM을 참조하십시오
 a| 
ILM(정보 수명 주기 관리) 작업에 대한 정보를 제공합니다.

* 스토리지 노드의 경우, 삭제 코딩 개체에 대한 ILM 평가 및 백그라운드 검증에 대한 세부 정보를 제공합니다.
* 각 사이트 및 전체 그리드에 대해 시간의 경과에 따른 ILM 대기열 그래프를 표시합니다.
* 전체 그리드에서 는 모든 개체에 대한 전체 ILM 스캔을 완료하는 데 필요한 예상 시간을 제공합니다.

 a| 
스토리지 노드, 각 사이트 및 전체 그리드



 a| 
로드 밸런서
 a| 
부하 분산 서비스와 관련된 성능 및 진단 그래프를 포함합니다.

* 각 사이트에 대해 해당 사이트의 모든 노드에 대한 통계를 집계한 요약을 제공합니다.
* 전체 그리드에서 는 모든 사이트에 대한 통계를 집계한 요약을 제공합니다.

 a| 
관리 노드 및 게이트웨이 노드, 각 사이트 및 전체 그리드



 a| 
플랫폼 서비스
 a| 
사이트의 S3 플랫폼 서비스 작업에 대한 정보를 제공합니다.
 a| 
있습니다



 a| 
SANtricity 시스템 관리자
 a| 
SANtricity 시스템 관리자에 대한 액세스를 제공합니다. SANtricity 시스템 관리자는 스토리지 컨트롤러에 대한 하드웨어 진단 및 환경 정보와 드라이브 관련 문제를 검토할 수 있습니다.
 a| 
스토리지 어플라이언스 노드

* 참고: * 스토리지 어플라이언스의 컨트롤러 펌웨어가 8.70 미만인 경우 SANtricity 시스템 관리자 탭이 나타나지 않습니다.

|===