---
permalink: sg5700/automating-installation-configuration-appliance-nodes-configure-sga-py-script.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, automate, automating, automation, automatic, install, installation, configuration, configure, configure-sga.py script, configure-sga.py 
summary: configure-sga.py 스크립트를 사용하면 기본 관리 노드의 설치 및 구성을 포함하여 StorageGRID 어플라이언스 노드에 대한 많은 설치 및 구성 작업을 자동화할 수 있습니다. 이 스크립트는 구성할 어플라이언스가 많은 경우 유용할 수 있습니다. 또한 스크립트를 사용하여 어플라이언스 구성 정보가 포함된 JSON 파일을 생성할 수도 있습니다. 
---
= configure-sga.py 스크립트를 사용하여 어플라이언스 노드의 설치 및 구성 자동화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
를 사용할 수 있습니다 `configure-sga.py` StorageGRID 어플라이언스 노드에 대한 여러 설치 및 구성 작업을 자동화하는 스크립트(기본 관리 노드 설치 및 구성 포함) 이 스크립트는 구성할 어플라이언스가 많은 경우 유용할 수 있습니다. 또한 스크립트를 사용하여 어플라이언스 구성 정보가 포함된 JSON 파일을 생성할 수도 있습니다.

.이 작업에 대해
* 이 어플라이언스는 랙에 설치되어 있고 네트워크에 연결되어 있으며 전원이 켜져 있습니다.
* 네트워크 링크 및 IP 주소는 StorageGRID 어플라이언스 설치 프로그램을 사용하여 기본 관리 노드에 대해 구성되었습니다.
* 기본 관리 노드를 설치하는 경우 해당 IP 주소를 알 수 있습니다.
* 다른 노드를 설치 및 구성하는 경우 기본 관리 노드가 배포되었으며 해당 IP 주소를 알고 있는 것입니다.
* 기본 관리 노드 이외의 모든 노드의 경우 StorageGRID 어플라이언스 설치 프로그램의 IP 구성 페이지에 나열된 모든 그리드 네트워크 서브넷이 기본 관리 노드의 그리드 네트워크 서브넷 목록에 정의되어 있습니다.
* 을(를) 다운로드했습니다 `configure-sga.py` 파일. 이 파일은 설치 아카이브에 포함되어 있거나 StorageGRID 어플라이언스 설치 프로그램에서 * 도움말 * > * 어플라이언스 설치 스크립트 * 를 클릭하여 액세스할 수 있습니다.



NOTE: 이 절차는 명령줄 인터페이스를 사용하는 일부 경험이 있는 고급 사용자를 위한 것입니다. 또는 StorageGRID 어플라이언스 설치 프로그램을 사용하여 구성을 자동화할 수도 있습니다. 를 누릅니다link:automating-appliance-configuration-using-storagegrid-appliance-installer.html["StorageGRID 어플라이언스 설치 프로그램을 사용하여 어플라이언스 구성 자동화"]

.단계
. Python 스크립트를 실행하기 위해 사용 중인 Linux 시스템에 로그인합니다.
. 스크립트 구문에 대한 일반적인 도움말과 사용 가능한 매개 변수 목록을 보려면 다음을 입력합니다.
+
[listing]
----
configure-sga.py --help
----
+
를 클릭합니다 `configure-sga.py` 스크립트는 5개의 하위 명령을 사용합니다.

+
** `advanced` BMC 구성을 포함한 고급 StorageGRID 어플라이언스 상호 작용의 경우 및 어플라이언스의 현재 구성이 포함된 JSON 파일 작성
** `configure` RAID 모드, 노드 이름 및 네트워킹 매개 변수를 구성하는 데 사용됩니다
** `install` StorageGRID 설치를 시작하는 데 사용됩니다
** `monitor` StorageGRID 설치를 모니터링하는 데 사용됩니다
** `reboot` 어플라이언스 재부팅용


+
하위 명령(advanced, configure, install, monitor 또는 reboot) 인수를 입력한 다음 를 입력합니다 `--help` 옵션 해당 하위 명령(+)에서 사용할 수 있는 옵션에 대한 자세한 정보를 제공하는 다른 도움말 텍스트가 표시됩니다
`configure-sga.py _subcommand_ --help`

. 어플라이언스 노드의 현재 구성을 확인하려면 다음 위치를 입력합니다 `_SGA-install-ip_` 어플라이언스 노드에 대한 IP 주소 중 하나(+)입니다
`configure-sga.py configure _SGA-INSTALL-IP_`
+
이 결과는 기본 관리 노드의 IP 주소와 관리, 그리드 및 클라이언트 네트워크에 대한 정보를 포함하여 어플라이언스에 대한 현재 IP 정보를 표시합니다.

+
[listing]
----
Connecting to +https://10.224.2.30:8443+ (Checking version and connectivity.)
2021/02/25 16:25:11: Performing GET on /api/versions... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/system-info... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/admin-connection... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/link-config... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/networks... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/system-config... Received 200

  StorageGRID Appliance
    Name:        LAB-SGA-2-30
    Node type:   storage

  StorageGRID primary Admin Node
    IP:        172.16.1.170
    State:     unknown
    Message:   Initializing...
    Version:   Unknown

  Network Link Configuration
    Link Status
          Link      State      Speed (Gbps)
          ----      -----      -----
          1         Up         10
          2         Up         10
          3         Up         10
          4         Up         10
          5         Up         1
          6         Down       N/A

    Link Settings
        Port bond mode:      FIXED
        Link speed:          10GBE

        Grid Network:        ENABLED
            Bonding mode:    active-backup
            VLAN:            novlan
            MAC Addresses:   00:a0:98:59:8e:8a  00:a0:98:59:8e:82

        Admin Network:       ENABLED
            Bonding mode:    no-bond
            MAC Addresses:   00:80:e5:29:70:f4

        Client Network:      ENABLED
            Bonding mode:    active-backup
            VLAN:            novlan
            MAC Addresses:   00:a0:98:59:8e:89  00:a0:98:59:8e:81

  Grid Network
    CIDR:      172.16.2.30/21 (Static)
    MAC:       00:A0:98:59:8E:8A
    Gateway:   172.16.0.1
    Subnets:   172.17.0.0/21
               172.18.0.0/21
               192.168.0.0/21
    MTU:       1500

  Admin Network
    CIDR:      10.224.2.30/21 (Static)
    MAC:       00:80:E5:29:70:F4
    Gateway:   10.224.0.1
    Subnets:   10.0.0.0/8
               172.19.0.0/16
               172.21.0.0/16
    MTU:       1500

  Client Network
    CIDR:      47.47.2.30/21 (Static)
    MAC:       00:A0:98:59:8E:89
    Gateway:   47.47.0.1
    MTU:       2000

##############################################################
#####   If you are satisfied with this configuration,    #####
##### execute the script with the "install" sub-command. #####
##############################################################
----
. 현재 설정에서 값을 변경해야 하는 경우 를 사용합니다 `configure` 하위 명령을 사용하여 업데이트합니다. 예를 들어, 어플라이언스가 기본 관리 노드에 연결하는 데 사용하는 IP 주소를 변경하려는 경우 `172.16.2.99`를 입력하고 다음을 입력합니다. +
`configure-sga.py configure --admin-ip 172.16.2.99 _SGA-INSTALL-IP_`
. 어플라이언스 구성을 JSON 파일로 백업하려면 를 사용하십시오 `advanced` 및 `backup-file` 하위 명령. 예를 들어, IP 주소가 있는 어플라이언스의 구성을 백업하려는 경우 `_SGA-INSTALL-IP_` 을(를) 라는 파일에 저장합니다 `appliance-SG1000.json`를 입력하고 다음을 입력합니다. +
`configure-sga.py advanced --backup-file appliance-SG1000.json _SGA-INSTALL-IP_`
+
구성 정보가 포함된 JSON 파일은 에서 스크립트를 실행한 디렉토리에 작성됩니다.

+

IMPORTANT: 생성된 JSON 파일의 최상위 노드 이름이 어플라이언스 이름과 일치하는지 확인하십시오. 숙련된 사용자이고 StorageGRID API에 대한 철저한 이해가 없는 경우 이 파일을 변경하지 마십시오.

. 어플라이언스 구성이 만족스러우면 를 사용하십시오 `install` 및 `monitor` 어플라이언스를 설치하기 위한 하위 명령: +
`configure-sga.py install --monitor _SGA-INSTALL-IP_`
. 어플라이언스를 재부팅하려면 + 를 입력합니다
`configure-sga.py reboot _SGA-INSTALL-IP_`

