---
permalink: sg5700/maintaining-sg5700-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: E2800 컨트롤러에서 SANtricity OS 소프트웨어를 업그레이드하거나, E5500SG 컨트롤러의 이더넷 링크 구성을 변경하거나, E2800 컨트롤러 또는 E5500SG 컨트롤러를 교체하거나, 특정 구성 요소를 교체해야 할 수 있습니다. 이 섹션의 절차에서는 어플라이언스가 이미 StorageGRID 시스템의 스토리지 노드로 구축되었다고 가정합니다. 
---
= SG5700 어플라이언스 유지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E2800 컨트롤러에서 SANtricity OS 소프트웨어를 업그레이드하거나, E5500SG 컨트롤러의 이더넷 링크 구성을 변경하거나, E2800 컨트롤러 또는 E5500SG 컨트롤러를 교체하거나, 특정 구성 요소를 교체해야 할 수 있습니다. 이 섹션의 절차에서는 어플라이언스가 이미 StorageGRID 시스템의 스토리지 노드로 구축되었다고 가정합니다.

.단계
* link:placing-appliance-into-maintenance-mode.html["유지보수 모드로 제품을 두십시오"]
* link:upgrading-santricity-os-on-storage-controller.html["스토리지 컨트롤러에서 SANtricity OS 업그레이드"]
* link:upgrading-drive-firmware-using-santricity-system-manager.html["SANtricity 시스템 관리자를 사용하여 드라이브 펌웨어를 업그레이드합니다"]
* link:replacing-e2800-controller.html["E2800 컨트롤러 교체"]
* link:replacing-e5700sg-controller.html["E5500SG 컨트롤러 교체"]
* link:replacing-other-hardware-components-sg5700.html["다른 하드웨어 구성 요소 교체"]
* link:changing-link-configuration-of-e5700sg-controller.html["E5500SG 컨트롤러의 링크 구성 변경"]
* link:changing-mtu-setting.html["MTU 설정을 변경하는 중입니다"]
* link:checking-dns-server-configuration.html["DNS 서버 구성을 확인하는 중입니다"]
* link:monitoring-node-encryption-in-maintenance-mode.html["유지보수 모드에서 노드 암호화 모니터링"]

