---
permalink: expand/configuring-expanded-storagegrid-system.html 
sidebar: sidebar 
keywords: expansion, configuration 
summary: 확장을 완료한 후에는 추가 통합 및 구성 단계를 수행해야 합니다. 
---
= 확장된 StorageGRID 시스템 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장을 완료한 후에는 추가 통합 및 구성 단계를 수행해야 합니다.

.이 작업에 대해
확장 시 추가하는 그리드 노드에 대해 아래 나열된 구성 작업을 완료해야 합니다. 시스템 설치 및 관리 시 선택한 옵션과 확장 중에 추가된 그리드 노드를 구성하는 방법에 따라 일부 작업은 선택 사항일 수 있습니다.

.단계
. 스토리지 노드를 추가한 경우 다음 구성 작업을 완료합니다.
+
[cols="2a,1a"]
|===
| 스토리지 노드 구성 작업 | 를 참조하십시오 


 a| 
ILM 규칙에 사용된 스토리지 풀을 검토하여 새 스토리지가 사용되는지 확인합니다.

** 사이트를 추가한 경우 사이트의 스토리지 풀을 생성하고 ILM 규칙을 업데이트하여 새 스토리지 풀을 사용합니다.
** 기존 사이트에 스토리지 노드를 추가한 경우 새 노드가 올바른 스토리지 등급을 사용하는지 확인합니다.
+
* 참고: * 기본적으로 새 스토리지 노드는 모든 스토리지 노드 스토리지 등급에 할당되며 사이트에 해당 등급을 사용하는 스토리지 풀에 추가됩니다. 새 노드에서 사용자 지정 스토리지 등급을 사용하려면 해당 노드를 수동으로 사용자 지정 등급(* ILM * > * 스토리지 등급 *)에 할당해야 합니다.


 a| 
link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]



 a| 
스토리지 노드가 객체를 인스팅하고 있는지 확인합니다.
 a| 
link:verifying-storage-node-is-active.html["스토리지 노드가 활성 상태인지 확인합니다"]



 a| 
삭제 코딩 데이터의 균형을 재조정합니다(권장 스토리지 노드 수를 추가할 수 없는 경우에만).
 a| 
link:rebalancing-erasure-coded-data-after-adding-storage-nodes.html["스토리지 노드를 추가한 후 삭제 코딩 데이터를 재조정합니다"]

|===
. 게이트웨이 노드를 추가한 경우 다음 구성 작업을 완료합니다.
+
[cols="2a,1a"]
|===
| 게이트웨이 노드 구성 작업 | 를 참조하십시오 


 a| 
고가용성 그룹이 클라이언트 연결에 사용되는 경우 게이트웨이 노드를 HA 그룹에 추가합니다. 구성 * > * 네트워크 설정 * > * 고가용성 그룹 * 을 선택하여 기존 HA 그룹 목록을 검토하고 새 노드를 추가합니다.
 a| 
link:../admin/index.html["StorageGRID 관리"]

|===
. 관리 노드를 추가한 경우 다음 구성 작업을 완료합니다.
+
[cols="2a,1a"]
|===
| 관리자 노드 구성 작업 | 를 참조하십시오 


 a| 
StorageGRID 시스템에 대해 SSO(Single Sign-On)를 사용하는 경우 새 관리 노드에 대한 AD FS(Active Directory Federation Services)에서 기반 당사자 신뢰를 만들어야 합니다. 이 신뢰할 수 있는 상대 트러스트를 만들 때까지 노드에 로그인할 수 없습니다.
 a| 
link:../admin/configuring-sso.html["Single Sign-On 구성"]



 a| 
관리 노드에서 로드 밸런서 서비스를 사용하려는 경우 고가용성 그룹에 관리 노드를 추가해야 할 수 있습니다. 구성 * > * 네트워크 설정 * > * 고가용성 그룹 * 을 선택하여 기존 HA 그룹 목록을 검토하고 새 노드를 추가합니다.
 a| 
link:../admin/index.html["StorageGRID 관리"]



 a| 
필요에 따라 각 관리 노드에서 속성과 감사 정보를 일관되게 유지하려면 운영 관리 노드에서 확장 관리 노드로 관리 노드 데이터베이스를 복사합니다.
 a| 
link:copying-admin-node-database.html["관리 노드 데이터베이스를 복사하는 중입니다"]



 a| 
필요에 따라 각 관리 노드에서 기간별 메트릭을 일관되게 유지하려면 Prometheus 데이터베이스를 기본 관리 노드에서 확장 관리 노드로 복사합니다.
 a| 
link:copying-prometheus-metrics.html["Prometheus 메트릭을 복사하는 중입니다"]



 a| 
필요에 따라 각 관리 노드에서 기록 로그 정보를 일관되게 유지하려면 기존 감사 로그를 기본 관리 노드에서 확장 관리 노드로 복사합니다.
 a| 
link:copying-audit-logs.html["감사 로그를 복사하는 중입니다"]



 a| 
필요한 경우 NFS 또는 CIFS 파일 공유를 통해 감사 목적으로 시스템에 대한 액세스를 구성합니다.

* 참고: * CIFS/Samba를 통한 감사 내보내기는 더 이상 사용되지 않으며 향후 StorageGRID 릴리스에서 제거될 예정입니다.
 a| 
link:../admin/index.html["StorageGRID 관리"]



 a| 
필요에 따라 알림에 대한 기본 설정 보낸 사람을 변경합니다. 확장 관리 노드를 기본 설정 보낸 사람으로 지정할 수 있습니다. 그렇지 않으면 기본 설정 송신자로 구성된 기존 관리 노드가 AutoSupport 메시지, SNMP 알림, 경고 이메일 및 알람 이메일(레거시 시스템)을 비롯한 알림을 계속 전송합니다.
 a| 
link:../admin/index.html["StorageGRID 관리"]

|===
. 아카이브 노드를 추가한 경우 다음 구성 작업을 완료합니다.
+
[cols="2a,1a"]
|===
| 노드 구성 작업을 아카이빙합니다 | 를 참조하십시오 


 a| 
대상 외부 아카이브 스토리지 시스템에 대한 아카이브 노드의 연결을 구성합니다. 확장을 완료하면 * ARC * > * Target * 구성 요소를 통해 연결 정보를 구성할 때까지 아카이브 노드는 알람 상태가 됩니다.
 a| 
link:../admin/index.html["StorageGRID 관리"]



 a| 
ILM 정책을 업데이트하여 새 아카이브 노드를 통해 개체 데이터를 아카이빙합니다.
 a| 
link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]



 a| 
아카이브 노드로부터 개체 데이터 검색의 속도와 효율성을 모니터링하는 데 사용되는 속성에 대한 사용자 지정 알람을 구성합니다.
 a| 
link:../admin/index.html["StorageGRID 관리"]

|===
. 신뢰할 수 없는 클라이언트 네트워크로 확장 노드가 추가되었는지 확인하거나 노드의 클라이언트 네트워크를 신뢰할 수 없는지 변경하려면 * 구성 * > * 네트워크 설정 * > * 신뢰할 수 없는 클라이언트 네트워크 * 로 이동하십시오.
+
확장 노드의 클라이언트 네트워크를 신뢰할 수 없는 경우 로드 밸런서 끝점을 사용하여 클라이언트 네트워크의 노드에 연결해야 합니다. 자세한 내용은 StorageGRID 관리 지침을 참조하십시오.

. DNS(Domain Name System)를 구성합니다.
+
각 그리드 노드에 대해 DNS 설정을 별도로 지정한 경우 새 노드에 대해 노드별 DNS 설정을 사용자 지정해야 합니다. 복구 및 유지 관리 지침 에서 단일 그리드 노드의 DNS 구성 수정에 대한 정보를 참조하십시오.

+
가장 좋은 방법은 각 사이트에서 로컬로 액세스할 수 있는 일부 DNS 서버를 그리드 전체 DNS 서버 목록에 포함하는 것입니다. 새 사이트를 추가한 경우 사이트에 대한 새 DNS 서버를 그리드 전체 DNS 구성에 추가합니다.

+

IMPORTANT: DNS 서버에 2-6개의 IPv4 주소를 제공합니다. 네트워크 연결 시 각 사이트에서 로컬로 액세스할 수 있는 DNS 서버를 선택해야 합니다. 이는 Is착륙한 사이트가 계속해서 DNS 서비스에 액세스할 수 있도록 하기 위한 것입니다. 그리드 전체 DNS 서버 목록을 구성한 후 각 노드에 대해 DNS 서버 목록을 추가로 사용자 지정할 수 있습니다. 자세한 내용은 복구 및 유지 관리 지침 에서 DNS 구성 수정에 대한 정보를 참조하십시오.

. 새 사이트를 추가한 경우 해당 사이트에서 NTP(Network Time Protocol) 서버에 액세스할 수 있는지 확인합니다.
+

IMPORTANT: 각 사이트에서 최소 2개의 노드가 4개 이상의 외부 NTP 소스에 액세스할 수 있는지 확인합니다. 사이트에서 하나의 노드만 NTP 소스에 연결할 수 있는 경우 해당 노드가 중단되면 타이밍 문제가 발생합니다. 또한 사이트당 두 노드를 기본 NTP 소스로 지정하면 사이트가 나머지 그리드에서 격리될 경우 정확한 시간을 보장할 수 있습니다.

+
자세한 내용은 복구 및 유지 관리 지침을 참조하십시오.



.관련 정보
link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

link:verifying-storage-node-is-active.html["스토리지 노드가 활성 상태인지 확인합니다"]

link:copying-admin-node-database.html["관리 노드 데이터베이스를 복사하는 중입니다"]

link:copying-prometheus-metrics.html["Prometheus 메트릭을 복사하는 중입니다"]

link:copying-audit-logs.html["감사 로그를 복사하는 중입니다"]

link:../upgrade/index.html["소프트웨어 업그레이드"]

link:../maintain/index.html["유지 및 복구"]
