---
permalink: ilm/comparing-s3-object-lock-to-legacy-compliance.html 
sidebar: sidebar 
keywords:  
summary:  
---
= S3 오브젝트 잠금을 레거시 규정 준수와 비교합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5의 S3 오브젝트 잠금 기능은 이전 StorageGRID 버전에서 사용할 수 있었던 규정 준수 기능을 대체합니다. 새로운 S3 오브젝트 잠금 기능이 Amazon S3 요구 사항을 준수하므로, 이제 ""레거시 규정 준수""라고 하는 독점적인 StorageGRID 규정 준수 기능을 더 이상 사용하지 않습니다.

이전에 글로벌 규정 준수 설정을 활성화한 경우 StorageGRID 11.5로 업그레이드하면 새로운 글로벌 S3 오브젝트 잠금 설정이 자동으로 활성화됩니다. 테넌트 사용자는 더 이상 StorageGRID 11.5에서 Compliance를 활성화한 상태로 새 버킷을 생성할 수 없지만, 필요에 따라 테넌트 사용자는 기존 레거시 준수 버킷을 계속 사용하고 관리할 수 있습니다. 여기에는 다음과 같은 작업이 포함됩니다.

* 레거시 규정 준수 기능이 활성화된 기존 버킷에 새 객체 인스팅
* 레거시 규정 준수를 활성화한 기존 버킷의 보존 기간 증가
* 레거시 규정 준수 기능이 활성화된 기존 버킷의 자동 삭제 설정을 변경합니다.
* 레거시 규정 준수 기능이 활성화된 기존 버킷에 법적 증거 자료 보관
* 법적 증거 자료 보관


https://["NetApp 기술 자료: StorageGRID 11.5에서 레거시 준수 버킷을 관리하는 방법"^]

이전 버전의 StorageGRID에서 레거시 규정 준수 기능을 사용한 경우 다음 표를 참조하여 StorageGRID의 S3 오브젝트 잠금 기능과 어떻게 다른지 알아보십시오.

[cols="1a,1a,1a"]
|===
|  | S3 오브젝트 잠금(신규) | 규정 준수(레거시) 


 a| 
이 기능은 전역적으로 어떻게 활성화됩니까?
 a| 
그리드 관리자에서 * 구성 * > * 시스템 설정 * > * S3 오브젝트 잠금 * 을 선택합니다.
 a| 
더 이상 지원되지 않습니다.

* 참고: * 이전에 글로벌 규정 준수 설정을 활성화한 경우 StorageGRID 11.5로 업그레이드하면 글로벌 S3 오브젝트 잠금 설정이 자동으로 활성화됩니다.



 a| 
버킷에 대한 기능은 어떻게 활성화됩니까?
 a| 
사용자는 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 새 버킷을 생성할 때 S3 오브젝트 잠금을 활성화해야 합니다.
 a| 
사용자는 더 이상 Compliance를 활성화한 상태로 새 버킷을 생성할 수 없지만 기존의 준수 버켓에 새 객체를 계속 추가할 수 있습니다.



 a| 
버킷 버전 관리가 지원됩니까?
 a| 
예. 버킷에 대해 S3 오브젝트 잠금이 활성화된 경우 버킷 버전 관리가 필요하며 자동으로 활성화됩니다.
 a| 
아니요 레거시 준수 기능은 버킷 버전 관리를 허용하지 않습니다.



 a| 
개체 보존은 어떻게 설정됩니까?
 a| 
사용자는 각 개체 버전에 대해 보존 종료 날짜를 설정할 수 있습니다.
 a| 
사용자는 전체 버킷의 보존 기간을 설정해야 합니다. 보존 기간은 버킷의 모든 객체에 적용됩니다.



 a| 
버킷에 보존 및 법적 보관에 대한 기본 설정이 있습니까?
 a| 
아니요 S3 오브젝트 잠금이 활성화된 StorageGRID 버킷에는 기본 보존 기간이 없습니다. 대신 각 개체 버전에 대해 보존 종료 날짜를 지정할 수 있습니다.
 a| 
예



 a| 
보존 기간을 변경할 수 있습니까?
 a| 
개체 버전의 보존 기한 은 늘릴 수 있지만 줄일 수는 없습니다.
 a| 
버킷의 보존 기간은 늘릴 수 있지만 줄일 수는 없습니다.



 a| 
법적 보류가 통제되는 곳은 어디입니까?
 a| 
사용자는 법적 증거 자료 보관 또는 버킷의 모든 개체 버전에 대한 법적 증거 자료 보관 장치를 들어 올릴 수 있습니다.
 a| 
법적 구속이 버킷에 배치되어 버킷의 모든 물체에 영향을 미칩니다.



 a| 
언제 오브젝트를 삭제할 수 있습니까?
 a| 
개체가 법적 증거 자료 보관 중이 아닌 경우, 보존 기한 에 도달한 후에 개체 버전을 삭제할 수 있습니다.
 a| 
버킷이 법적 증거 자료 보관 중이 아닌 경우, 보존 기간이 만료된 후에는 오브젝트를 삭제할 수 있습니다. 개체를 자동으로 또는 수동으로 삭제할 수 있습니다.



 a| 
버킷 라이프사이클 구성이 지원됩니까?
 a| 
예
 a| 
아니요

|===