---
permalink: ilm/how-objects-are-ingested.html 
sidebar: sidebar 
keywords:  
summary: StorageGRID는 동기식 배치를 수행하거나 개체와 일치하는 ILM 규칙에 지정된 대로 이중 커밋을 수행하여 수집 중에 개체를 보호합니다. 
---
= 오브젝트를 섭취하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID는 동기식 배치를 수행하거나 개체와 일치하는 ILM 규칙에 지정된 대로 이중 커밋을 수행하여 수집 중에 개체를 보호합니다.

S3 또는 Swift 클라이언트가 오브젝트를 그리드에 저장하는 경우 StorageGRID는 다음 두 가지 방법 중 하나를 사용하여 오브젝트를 수집합니다.

* * 동기식 배치 *: StorageGRID는 ILM 요구 사항을 충족하는 데 필요한 모든 오브젝트 복사본을 즉시 생성합니다. StorageGRID는 모든 복제본이 생성될 때 ""수집 성공"" 메시지를 클라이언트에 보냅니다.
+
StorageGRID에서 모든 오브젝트 복사본을 즉시 생성할 수 없는 경우(예: 필요한 위치를 일시적으로 사용할 수 없음) "'수집 실패' 메시지를 클라이언트에 보냅니다. 또는 ILM 규칙을 만들 때 선택한 사항에 따라 나중에 중간 개체 복사본을 만들고 ILM을 평가하는 것으로 되돌아갑니다.

* * 이중 커밋 *: StorageGRID는 즉시 두 개의 임시 객체 복사본을 서로 다른 스토리지 노드에 생성하고 ""수집 성공" 메시지를 클라이언트에 보냅니다. 그런 다음 StorageGRID가 ILM 평가를 위해 개체를 대기열에 넣습니다.
+
StorageGRID에서 ILM 평가를 수행하면 먼저 임시 복사본이 ILM 규칙의 배치 지침을 충족하는지 확인합니다. 예를 들어, 두 개의 중간 복사본이 2개의 복사본 ILM 규칙의 지침을 충족하지만 삭제 코딩 규칙의 지침은 충족하지 않을 수 있습니다. 임시 복사본이 ILM 지침을 충족하지 않으면 StorageGRID은 새 개체 복사본을 만들고 필요하지 않은 중간 복사본을 삭제합니다.

+
StorageGRID에서 두 개의 중간 복사본을 만들 수 없는 경우(예: 네트워크 문제로 인해 두 번째 복사본이 만들어지는 것을 방지) StorageGRID는 다시 시도하지 않습니다. 수집 실패.

+

NOTE: S3 또는 Swift 클라이언트는 다음을 지정하여 수집 시 StorageGRID가 단일 중간 복사본을 생성하도록 지정할 수 있습니다 `REDUCED_REDUNDANCY` 를 참조하십시오. 자세한 내용은 S3 또는 Swift 클라이언트 구현 지침을 참조하십시오.



기본적으로 StorageGRID는 동기식 배치를 사용하여 수집 중에 오브젝트를 보호합니다.

.관련 정보
link:data-protection-options-for-ingest.html["데이터 보호를 위한 수집 옵션"]

link:../s3/index.html["S3을 사용합니다"]

link:../swift/index.html["Swift를 사용합니다"]
