---
permalink: fabricpool/example-ilm-policy-for-fabricpool-data.html 
sidebar: sidebar 
keywords: fabricPool, ilm, information lifecycle management, ILM policy, example 
summary: 이 간단한 예제 정책을 자신의 ILM 규칙 및 정책의 시작 지점으로 사용합니다. 
---
= FabricPool 데이터에 대한 ILM 정책의 예
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 간단한 예제 정책을 자신의 ILM 규칙 및 정책의 시작 지점으로 사용합니다.

이 예제에서는 콜로라도주 덴버의 단일 데이터 센터에 4개의 스토리지 노드가 있는 StorageGRID 시스템에 대한 ILM 규칙 및 ILM 정책을 디자인한다고 가정합니다. 이 예제의 FabricPool 데이터는 이라는 이름의 버킷을 사용합니다 `fabricpool-bucket`.

[CAUTION]
====
다음 ILM 규칙 및 정책은 예일 뿐입니다. ILM 규칙을 구성하는 방법은 여러 가지가 있습니다. 새 정책을 활성화하기 전에 제안된 정책을 시뮬레이션하여 콘텐츠가 손실로부터 보호되도록 의도한 대로 동작하는지 확인합니다.

자세한 내용: link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

====
.단계
. 이름이 * den * 인 스토리지 풀을 생성합니다. 덴버 사이트를 선택합니다.
. 이름이 * 2와 1 * 인 삭제 코딩 프로필을 만듭니다. 2+1 삭제 코딩 체계와 * den * 스토리지 풀을 선택합니다.
. 의 데이터에만 적용되는 ILM 규칙을 만듭니다 `fabricpool-bucket`. 이 예제 규칙은 삭제 코딩 복사본을 만듭니다.
+
[cols="1a,1a"]
|===
| 규칙 정의 | 예제 값 


 a| 
규칙 이름
 a| 
FabricPool 데이터에 2개 이상의 삭제 코딩



 a| 
버킷 이름
 a| 
`fabricpool-bucket`

FabricPool 테넌트 계정에서도 필터링할 수 있습니다.



 a| 
고급 필터링
 a| 
객체 크기(MB)가 0.2 MB를 초과합니다.

* 참고: * FabricPool는 4MB 객체만 쓰지만 이 규칙은 삭제 코딩을 사용하므로 객체 크기 필터를 추가해야 합니다.



 a| 
참조 시간
 a| 
수집 시간



 a| 
배치
 a| 
0일째부터 영원히



 a| 
유형
 a| 
삭제 코딩



 a| 
위치
 a| 
DEN(2 + 1)



 a| 
수집 동작
 a| 
균형

|===
. 첫 번째 규칙과 일치하지 않는 개체의 복제된 복사본 2개를 생성하는 ILM 규칙을 생성합니다. 기본 필터(테넌트 계정 또는 버킷 이름) 또는 고급 필터를 선택하지 마십시오.
+
[cols="1a,1a"]
|===
| 규칙 정의 | 예제 값 


 a| 
규칙 이름
 a| 
2개의 복제 복사본



 a| 
버킷 이름
 a| 
_없음_



 a| 
고급 필터링
 a| 
_없음_



 a| 
참조 시간
 a| 
수집 시간



 a| 
배치
 a| 
0일째부터 영원히



 a| 
유형
 a| 
복제됨



 a| 
위치
 a| 
수



 a| 
사본
 a| 
2



 a| 
수집 동작
 a| 
균형

|===
. 제안된 ILM 정책을 생성하고 두 규칙을 선택합니다. 복제 규칙에서는 필터를 사용하지 않으므로 정책의 기본(마지막) 규칙일 수 있습니다.
. 테스트 오브젝트를 그리드에 수집.
. 테스트 개체를 사용하여 정책을 시뮬레이션하여 동작을 확인합니다.
. 정책을 활성화합니다.


이 정책이 활성화되면 StorageGRID는 다음과 같이 오브젝트 데이터를 배치합니다.

* 데이터는 의 FabricPool에서 계층화합니다 `fabricpool-bucket` 2+1 삭제 코딩 체계를 사용하여 삭제 코딩됩니다. 데이터 조각 2개와 패리티 조각 1개가 서로 다른 스토리지 노드 3개에 배치됩니다.
* 다른 모든 버킷의 모든 객체가 복제됩니다. 두 개의 복제본이 생성되고 두 개의 서로 다른 스토리지 노드에 배치됩니다.
* 삭제 코딩 및 복제된 복사본은 S3 클라이언트에서 삭제할 때까지 StorageGRID에서 유지됩니다. StorageGRID ILM은 이러한 항목을 삭제하지 않습니다.

